Repository google/timesketch, pull requests merged in 2018-03, with the labels that each got.

#553 e2e tests fix
  vagrant/bootstrap.sh
Labels: Bug

#561 Update momentjs
  package.json
  timesketch/ui/explore/filter.directive.ts
  yarn.lock
Labels: Code health

#551 Strip domain from username if present
  timesketch/views/sketch.py
Labels: Bug

#573 Don't build pager when there are no results
  timesketch/ui/explore/event-list.html
  timesketch/ui/explore/event.directive.ts
  timesketch/ui/explore/search.directive.ts
Labels: Bug

#574 Remove unused abstraction base class
  timesketch/api/v1/resources.py
  timesketch/lib/aggregators.py
  timesketch/lib/datastore.py
  timesketch/lib/datastores/elastic.py
  timesketch/lib/testlib.py
  timesketch/views/sketch.py
Labels: Code health

#576 Enable file import/export support for search templates.
  timesketch/models/sketch.py
  tsctl
Labels: Feature request

#577 add label support to search templates
  tsctl
Labels: Feature request
