Repository google/timesketch, pull requests merged in 2018-12, with the labels that each got.

#729 Add emoji support in the UI and in analyzers
  timesketch/lib/analyzers/interface.py
  timesketch/lib/definitions.py
  timesketch/static/dist/bundle.js
  timesketch/ui/app.module.ts
  timesketch/ui/explore/event.html
Labels: New feature, UI/UX

#730 Move emojis to the left
  timesketch/ui/explore/event.html
Labels: UI/UX

#731 Don't remove session when engine is created
  timesketch/models/__init__.py
Labels: Bug

#732 Set human readable strings
  timesketch/lib/analyzers/interface.py
Labels: New feature

#742 Add definitions for emojis
  timesketch/lib/analyzers/browser_search.py
  timesketch/lib/emojis.py
Labels: Feature request

#744 Changed set_human_readable so that it does not overwrite previous data
  timesketch/lib/analyzers/interface.py
Labels: Code health

#756 Only create saved view if there are hits
  timesketch/lib/analyzers/browser_search.py
Labels: Bug

#752 Upgrade urllib3 due to security fix
  requirements.in
  requirements.txt
Labels: Bug

#751 Run index analyzers in a chain
  timesketch/lib/tasks.py
Labels: Bug
