Repository google/timesketch, pull requests merged in 2018-11, with the labels that each got.

#679 Max CSV field size
  timesketch/lib/utils.py
Labels: Bug

#709 Enable similarity UI element
  timesketch.conf
  timesketch/views/sketch.py
Labels: Bug, Code health

#703 The former wiki link no longer exists
  timesketch/templates/sketch/timelines.html
Labels: Documentation

#698 minor fixes for docker files
  docker/Dockerfile
  docker/docker-compose.yml
Labels: Bug

#717 Bug fixes for the analyzers
  timesketch/lib/analyzers/interface.py
Labels: Bug

#718 Development environment with Docker
  docker/Dockerfile-dev
  docker/timesketch-dev-compose.yml
  docker/timesketch-dev-entrypoint.sh
Labels: New feature
