Repository google/timesketch, pull requests merged in 2018-05, with the labels that each got.

#593 Enable upload by default when using Vagrant
  vagrant/bootstrap.sh
Labels: Bug

#594 Consistent null state
  timesketch/templates/sketch/explore.html
  timesketch/templates/sketch/overview.html
  timesketch/templates/sketch/stories.html
  timesketch/templates/sketch/timelines.html
  timesketch/templates/sketch/views.html
  timesketch/ui/sketch/search-template-list.html
  timesketch/ui/sketch/views-list.html
  timesketch/ui/story/list.html
  timesketch/views/sketch.py
Labels: Bug, Code health

#597 Fixed a typo
  docs/Community-Guide.md
Labels: Bug

#598 Parameterize Timesketch authentication with docker-compose
  docker/docker-compose.yml
Labels: Feature request

#606 Add MICROSECONDS_PER_SECOND to definitions
  timesketch/lib/definitions.py
Labels: Feature request
