Repository google/timesketch, pull requests merged in 2018-06, with the labels that each got.

#619 Fix broken context query
  timesketch/ui/explore/event-add.html
  timesketch/ui/explore/event-list.html
  timesketch/ui/explore/event.directive.ts
Labels: Bug

#617 Google IAP/OIDC authentication support
  requirements.in
  requirements.txt
  timesketch.conf
  timesketch/lib/google_jwt.py
  timesketch/lib/google_jwt_test.py
  timesketch/views/auth.py
Labels: Feature request

#612 Close DB session in tasks
  timesketch/lib/tasks.py
Labels: Bug

#613 Rename cypher lib dir
  timesketch/api/v1/resources.py
  timesketch/lib/cypher/__init__.py
  timesketch/lib/cypher/append_return_clause.py
  timesketch/lib/cypher/append_return_clause_test.py
  timesketch/lib/cypher/insertable_string.py
  timesketch/lib/cypher/invalid_query.py
  timesketch/lib/cypher/restrict_query_to_sketch.py
  timesketch/lib/cypher/restrict_query_to_sketch_test.py
  timesketch/lib/cypher/transpile_query.py
  timesketch/lib/cypher/transpile_query_test.py
  timesketch/lib/cypher/unwind_timestamps.py
  timesketch/lib/cypher/unwind_timestamps_test.py
Labels: Code health

#603 Redline Import in tsctl
  timesketch/lib/utils.py
  tsctl
Labels: New feature
