Repository google/timesketch, pull requests merged in 2019-01, with the labels that each got.

#761 Added a phishy domain analyzer
  timesketch.conf
  timesketch/lib/analyzers/__init__.py
  timesketch/lib/analyzers/manager_test.py
  timesketch/lib/analyzers/phishy_domains.py
  timesketch/lib/analyzers/phishy_domains_test.py
Labels: New feature

#762 Changed the emoji library to include helper text
  timesketch/lib/analyzers/browser_search.py
  timesketch/lib/analyzers/phishy_domains.py
  timesketch/lib/emojis.py
  timesketch/lib/emojis_test.py
Labels: UI/UX

#767 Added dependencies into analyzers to affect ordering they are run in.
  timesketch/lib/analyzers/browser_search.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/analyzers/manager.py
  timesketch/lib/analyzers/manager_test.py
  timesketch/lib/analyzers/similarity_scorer.py
Labels: New feature

#768 UI polish for the new year
  timesketch/static/dist/bundle.css
  timesketch/static/dist/bundle.js
  timesketch/templates/home/home.html
  timesketch/templates/sketch/overview.html
  timesketch/ui/app.module.ts
  timesketch/ui/css/ts.scss
Labels: UI/UX

#770 New importer in tsctl
  contrib/timesketch-importer.conf
  contrib/timesketch-importer.service
  contrib/timesketch-importer.sh
  setup.py
  timesketch/models/__init__.py
  tsctl
Labels: Code health, New feature

#775 Email send bugfix
  timesketch/lib/tasks.py
Labels: Bug

#780 Fixed a bug in the jsonl importer.
  timesketch/lib/analyzers/interface.py
  timesketch/lib/utils.py
Labels: Bug

#783 Adding a login analyzer.
  timesketch/lib/analyzers/__init__.py
  timesketch/lib/analyzers/login.py
  timesketch/lib/analyzers/login_test.py
  timesketch/lib/emojis.py
Labels: Analyzer idea, New feature

#785 Added a feature extraction analyzer
  MANIFEST.in
  config/features.yaml
  docker/Dockerfile
  docker/timesketch-dev-entrypoint.sh
  setup.py
  timesketch/lib/analyzers/__init__.py
  timesketch/lib/analyzers/feature_extraction.py
  timesketch/lib/analyzers/feature_extraction_test.py
  timesketch/lib/analyzers/interface.py
  vagrant/bootstrap.sh
Labels: Analyzer idea, New feature

#787 Added pandas support into the API and analyzers interface.
  api_client/python/timesketch_api_client/client.py
  requirements.txt
  timesketch/lib/analyzers/interface.py
Labels: New feature

#791 Added scrolling support to API calls
  api_client/python/timesketch_api_client/client.py
  timesketch/api/v1/resources.py
  timesketch/api/v1/resources_test.py
  timesketch/lib/forms.py
Labels: Code health

#794 Changed the login analyzer's logon event parsing.
  timesketch/lib/analyzers/login.py
Labels: Bug

#796 Minor bugs in the client library as well as adding timeline name + proper datetime
  api_client/python/setup.py
  api_client/python/timesketch_api_client/client.py
Labels: Bug, Code health

#801 Removed BeautifulSoup from requirements
  requirements.in
  requirements.txt
Labels: Code health

#802 Added mybinder config to TS, making it possible to run jupyterlab notebooks.
  README.md
  binder/requirements.txt
  notebooks/jupyter-timesketch-demo.ipynb
Labels: Code health

#811 Added a browser timeframe analyzer plugin
  timesketch/lib/analyzers/__init__.py
  timesketch/lib/analyzers/browser_timeframe.py
  timesketch/lib/analyzers/browser_timeframe_test.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/analyzers/utils.py
  timesketch/lib/analyzers/utils_test.py
  timesketch/lib/emojis.py
Labels: New feature
