Repository google/timesketch, pull requests merged in 2019-05, with the labels that each got.

#878 Update dependencies
  package.json
  requirements.txt
  timesketch/api/v1/resources.py
  timesketch/lib/testlib.py
Labels: Code health

#893 Changed phishy domain analyzer to return early if no results.
  timesketch/lib/analyzers/phishy_domains.py
Labels: Bug

#894 Minor bug fixes in CSV file import for python3 compatability
  timesketch/lib/tasks.py
  timesketch/lib/utils.py
Labels: Bug, Code health

#897 Commit Sketch object to DB before setting ACL
  timesketch/views/home.py
Labels: Bug

#898 Exit early if there are no domains to analyze
  timesketch/lib/analyzers/domain.py
Labels: Bug

#899 Use legacy aggregators in old UI
  timesketch/static/dist/bundle.js
  timesketch/ui/api/api.service.ts
Labels: Bug
