Repository google/timesketch, pull requests merged in 2019-11, with the labels that each got.

#994 Adding a chain analyzer.
  timesketch/lib/analyzers/__init__.py
  timesketch/lib/analyzers/chain.py
  timesketch/lib/analyzers/chain_plugins/__init__.py
  timesketch/lib/analyzers/chain_plugins/interface.py
  timesketch/lib/analyzers/chain_plugins/manager.py
  timesketch/lib/analyzers/chain_plugins/win_prefetch.py
  timesketch/lib/analyzers/chain_test.py
  timesketch/lib/emojis.py
Labels: Analyzer idea, New feature

#1021 Fixing bug in listing stored aggregators
  api_client/python/setup.py
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/importer.py
Labels: Bug

#1023 New UI: Just show delete menu if user has permission
  timesketch/api/v1/resources.py
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.5059a7f1.js
  timesketch/frontend/dist/js/chunk-common.5059a7f1.js.map
  timesketch/frontend/dist/js/chunk-common.a3d449c0.js
  timesketch/frontend/dist/js/chunk-common.a3d449c0.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/views/SketchOverview.vue
Labels: Bug

#1027 Adding OAUTH support to API client.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/client.py
  config/travis/install.sh
  data/timesketch.conf
  requirements.txt
  timesketch/lib/google_auth.py
  timesketch/lib/google_auth_test.py
  timesketch/views/auth.py
Labels: New feature

#1030 Changes to the OAUTH support for the client API
  api_client/python/setup.py
  api_client/python/timesketch_api_client/client.py
  timesketch/lib/google_auth.py
  timesketch/views/auth.py
Labels: Code health

#1031 Changing the OAUTH flow in the client to add a web server to catch response
  api_client/python/setup.py
  api_client/python/timesketch_api_client/client.py
Labels: Code health

#1032 Fix views in story mode
  timesketch/frontend/dist/css/chunk-common.5208dd60.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.05a332f7.js
  timesketch/frontend/dist/js/chunk-common.05a332f7.js.map
  timesketch/frontend/dist/js/chunk-common.1a42da61.js
  timesketch/frontend/dist/js/chunk-common.1a42da61.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/EventList.vue
  timesketch/frontend/src/components/Sketch/EventListCompact.vue
  timesketch/frontend/src/components/Sketch/EventListRow.vue
Labels: Bug

#1033 Bugfix for views without fields
  timesketch/frontend/dist/css/chunk-common.1083c54a.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.0e2bc98c.js
  timesketch/frontend/dist/js/chunk-common.0e2bc98c.js.map
  timesketch/frontend/dist/js/chunk-common.1a42da61.js
  timesketch/frontend/dist/js/chunk-common.1a42da61.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/EventListCompact.vue
  timesketch/frontend/src/components/Sketch/EventListRow.vue
  timesketch/frontend/src/views/SketchExplore.vue
Labels: Bug

#1034 Small bugfix for word wraps
  timesketch/frontend/dist/css/chunk-common.8f2e244a.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.0e2bc98c.js
  timesketch/frontend/dist/js/chunk-common.0e2bc98c.js.map
  timesketch/frontend/dist/js/chunk-common.9a059ac2.js
  timesketch/frontend/dist/js/chunk-common.9a059ac2.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/EventListCompact.vue
  timesketch/frontend/src/components/Sketch/EventListRow.vue
  timesketch/frontend/src/views/SketchExplore.vue
Labels: Bug

#1036 Adding description and chart titles for aggregation.
  timesketch/api/v1/resources.py
  timesketch/lib/aggregators/bucket.py
  timesketch/lib/aggregators/interface.py
  timesketch/lib/aggregators/term.py
  timesketch/lib/charts/barchart.py
  timesketch/lib/charts/interface.py
Labels: Code health

#1038 Adding aggregation information to the API and API client.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/client.py
  timesketch/api/v1/resources.py
  timesketch/api/v1/routes.py
  timesketch/lib/aggregators/interface.py
Labels: Code health

#1041 New UI: Bugfix for sharing form
  timesketch/frontend/dist/css/chunk-vendors.534842e8.css
  timesketch/frontend/dist/css/chunk-vendors.7ec8b058.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.55daac48.js
  timesketch/frontend/dist/js/chunk-common.55daac48.js.map
  timesketch/frontend/dist/js/chunk-common.798c68be.js
  timesketch/frontend/dist/js/chunk-common.798c68be.js.map
  timesketch/frontend/dist/js/chunk-vendors.8813ff27.js
  timesketch/frontend/dist/js/chunk-vendors.c957e138.js
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/ShareForm.vue
  timesketch/frontend/src/utils/RestApiClient.js
Labels: Bug

#1042 Bugfix: Do not strip domain when changing ACL
  timesketch/api/v1/resources.py
Labels: Bug

#1044 Splitting up parsing of large CSV files with the importer
  api_client/python/timesketch_api_client/importer.py
Labels: Code health
