Repository google/timesketch, pull requests merged in 2019-09, with the labels that each got.

#979 Remove Vagrant
  vagrant/README.md
  vagrant/Vagrantfile
  vagrant/bootstrap.sh
  vagrant/celery.conf
  vagrant/celery.service
  vagrant/test.csv
  vagrant/test.plaso
  vagrant/tmpfiles.d/celery.conf
Labels: Code health

#982 Fixing aggregations in the API client
  api_client/python/setup.py
  api_client/python/timesketch_api_client/client.py
  timesketch/api/v1/resources.py
Labels: Bug, New feature

#983 Making changes to how aggregations are done in API client
  api_client/python/setup.py
  api_client/python/timesketch_api_client/client.py
Labels: Code health

#984 Minor bug in client.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/client.py
Labels: Bug

#985 Adding aggregation into the jupyter notebook demo
  api_client/python/timesketch_api_client/client.py
  notebooks/jupyter-timesketch-demo.ipynb
Labels: Code health
