Repository google/timesketch, pull requests merged in 2019-06, with the labels that each got.

#889 Adding more aggregation APIs and upgrading API client to make use of them.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/client.py
  timesketch/api/v1/resources.py
  timesketch/api/v1/resources_test.py
  timesketch/api/v1/routes.py
  timesketch/lib/charts/barchart.py
  timesketch/lib/charts/interface.py
  timesketch/lib/forms.py
  timesketch/models/sketch.py
Labels: New feature

#903 Docker refactor
  docker/README.md
  docker/development/Dockerfile
  docker/development/README.md
  docker/development/docker-compose.yml
  docker/development/docker-entrypoint.sh
  docker/factory/README.md
  docker/factory/development/Dockerfile
Labels: Code health

#907 Adding starred event lookups to colab example
  notebooks/colab-timesketch-demo.ipynb
Labels: Code health

#911 New timeline picker component
  timesketch/frontend/dist/js/app.e3835b2d.js
  timesketch/frontend/src/components/SketchExplore.vue
  timesketch/frontend/src/components/SketchExploreSearch.vue
  timesketch/frontend/src/components/SketchExploreTimelinePicker.vue
Labels: UI/UX

#915 Fixing wrong file locations in docker configs
  docker/Dockerfile
  docker/development/docker-entrypoint.sh
Labels: Bug
