Repository google/timesketch, pull requests merged in 2020-08, with the labels that each got.

#1316 Added scrolling support into export API call
  api_client/python/timesketch_api_client/sketch.py
  timesketch/api/v1/resources/archive.py
  timesketch/lib/datastores/elastic.py
Labels: cla: yes

#1315 Sketch overview More Dialog Documentation
  docs/SketchOverview.md
  docs/images/SketchMore.png
Labels: cla: yes

#1325 Mention 8 GB as recommended RAM
  docker/dev/README.md
  docs/Installation.md
Labels: Documentation, cla: yes

#1318 Initial stab at API client documentation
  docs/APIClient.md
Labels: Documentation, cla: yes

#1317 Added the ability to export events (not yet in the UI)
  api_client/python/timesketch_api_client/aggregation.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
  config/dpkg/changelog
  timesketch/api/v1/export.py
  timesketch/api/v1/resources/aggregation.py
  timesketch/api/v1/resources/archive.py
  timesketch/api/v1/resources/explore.py
  timesketch/lib/charts/barchart.py
  timesketch/lib/forms.py
  timesketch/version.py
Labels: cla: yes

#1329 remove heatmap and manual events from userdoc
  docs/Users-Guide.md
Labels: Documentation, cla: yes

#1333 Fix a missing space
  docs/UseSigmaAnalyzer.md
Labels: cla: yes

#1321 Added an EVTX Gap analyzer and fixed logging (filter out ES logs)
  timesketch/api/v1/export.py
  timesketch/app.py
  timesketch/lib/analyzers/__init__.py
  timesketch/lib/analyzers/browser_search.py
  timesketch/lib/analyzers/domain.py
  timesketch/lib/analyzers/feature_extraction.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/analyzers/login.py
  timesketch/lib/analyzers/phishy_domains.py
  timesketch/lib/analyzers/safebrowsing.py
  timesketch/lib/analyzers/sigma_tagger.py
  timesketch/lib/analyzers/win_evtxgap.py
  timesketch/lib/analyzers/win_evtxgap_test.py
  timesketch/lib/tasks.py
  timesketch/lib/utils.py
  timesketch/wsgi.py
Labels: New feature, cla: yes

#1330 Add tabbed view of sketch list
  timesketch/api/v1/resources/sketch.py
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.14e26855.js
  timesketch/frontend/dist/js/chunk-common.14e26855.js.map
  timesketch/frontend/dist/js/chunk-common.beb1c7ca.js
  timesketch/frontend/dist/js/chunk-common.beb1c7ca.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Home/SketchList.vue
  timesketch/frontend/src/views/Home.vue
Labels: cla: yes

#1337 Minor change to the EVTX Gap analyzer
  timesketch/lib/analyzers/win_evtxgap.py
Labels: cla: yes

#1331 UI: Display Data Sources per Timeline & Make them Clickable
  timesketch/api/v1/resources/sketch.py
  timesketch/api/v1/utils.py
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
Labels: UI/UX, cla: yes

#1340 Pagination bugfix
  timesketch/frontend/dist/css/chunk-common.89725940.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.14e26855.js
  timesketch/frontend/dist/js/chunk-common.14e26855.js.map
  timesketch/frontend/dist/js/chunk-common.424b590a.js
  timesketch/frontend/dist/js/chunk-common.424b590a.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/views/SketchExplore.vue
Labels: cla: yes

#1342 Changing exports to export all events and include all columns
  timesketch/api/v1/export.py
  timesketch/api/v1/resources/explore.py
Labels: Code health, cla: yes

#1343 UI: Add export button for search results
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.424b590a.js
  timesketch/frontend/dist/js/chunk-common.424b590a.js.map
  timesketch/frontend/dist/js/chunk-common.b61eca6b.js
  timesketch/frontend/dist/js/chunk-common.b61eca6b.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/utils/RestApiClient.js
  timesketch/frontend/src/views/SketchExplore.vue
  timesketch/frontend/src/views/SketchOverview.vue
Labels: Feature request, UI/UX, cla: yes

#1344 Fixing an issue with the export functionality.
  timesketch/api/v1/export.py
Labels: Bug, cla: yes

#1345 Only aggregate stats if sketch have timelines
  timesketch/api/v1/resources/sketch.py
Labels: cla: yes

#1336 Refactor Documentation / Introduce admin guide
  docs/Admin-Guide.md
  docs/Users-Guide.md
Labels: Documentation, cla: yes

#1347 Display datetime based on timestamp
  timesketch/frontend/dist/css/chunk-common.f84d44b3.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.7a528aee.js
  timesketch/frontend/dist/js/chunk-common.7a528aee.js.map
  timesketch/frontend/dist/js/chunk-common.b61eca6b.js
  timesketch/frontend/dist/js/chunk-common.b61eca6b.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/EventList.vue
  timesketch/frontend/src/components/Sketch/EventListRow.vue
  timesketch/frontend/src/filters/Capitalize.js
  timesketch/frontend/src/filters/FormatTimestamp.js
  timesketch/frontend/src/views/SketchExplore.vue
Labels: cla: yes

#1349 Optimize UI for quicker archive
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.7a528aee.js
  timesketch/frontend/dist/js/chunk-common.7a528aee.js.map
  timesketch/frontend/dist/js/chunk-common.7ba1d1df.js
  timesketch/frontend/dist/js/chunk-common.7ba1d1df.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/views/Home.vue
  timesketch/frontend/src/views/SketchOverview.vue
Labels: cla: yes

#1350 Filter for events that have comments
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.7ba1d1df.js
  timesketch/frontend/dist/js/chunk-common.7ba1d1df.js.map
  timesketch/frontend/dist/js/chunk-common.8708b486.js
  timesketch/frontend/dist/js/chunk-common.8708b486.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/filters/FilterChip.js
  timesketch/frontend/src/views/SketchExplore.vue
Labels: cla: yes

#1348 Various Changes With Analyzers
  timesketch/api/v1/export.py
  timesketch/api/v1/resources/aggregation.py
  timesketch/lib/analyzers/browser_search.py
  timesketch/lib/analyzers/browser_timeframe.py
  timesketch/lib/analyzers/chain.py
  timesketch/lib/analyzers/chain_plugins/__init__.py
  timesketch/lib/analyzers/chain_plugins/chrome_download_file.py
  timesketch/lib/analyzers/chain_plugins/interface.py
  timesketch/lib/analyzers/chain_plugins/win_prefetch.py
  timesketch/lib/analyzers/chain_test.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/testlib.py
  timesketch/lib/utils.py
Labels: cla: yes
