Repository google/timesketch, pull requests merged in 2020-07, with the labels that each got.

#1171 Safe Browsing API url analyzer
  config/dpkg/control
  data/timesketch.conf
  requirements.txt
  timesketch/lib/analyzers/__init__.py
  timesketch/lib/analyzers/safebrowsing.py
  timesketch/lib/analyzers/safebrowsing_test.py
Labels: New feature, cla: yes

#1288 Importer: moving version information to a separate file, adding an init file to fix packaging.
  importer_client/python/setup.py
  importer_client/python/timesketch_import_client/version.py
  importer_client/python/tools/__init__.py
  importer_client/python/tools/timesketch_importer.py
Labels: Code health, cla: yes

#1290 Changed logger configuration
  api_client/python/timesketch_api_client/aggregation.py
  api_client/python/timesketch_api_client/analyzer.py
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/config.py
  api_client/python/timesketch_api_client/crypto.py
  api_client/python/timesketch_api_client/index.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/story.py
  api_client/python/timesketch_api_client/timeline.py
  api_client/python/timesketch_api_client/version.py
  importer_client/python/timesketch_import_client/data/__init__.py
  importer_client/python/timesketch_import_client/helper.py
  importer_client/python/timesketch_import_client/importer.py
  importer_client/python/timesketch_import_client/version.py
  importer_client/python/tools/timesketch_importer.py
  timesketch/api/v1/resources/archive.py
  timesketch/api/v1/resources/event.py
  timesketch/api/v1/resources/searchindex.py
  timesketch/api/v1/resources/sketch.py
  timesketch/api/v1/resources/user.py
  timesketch/lib/datastores/elastic.py
Labels: cla: yes

#1289 [Docker-doc] How to run tests
  docker/dev/README.md
Labels: cla: yes

#1291 Tag GCS events in Cloud logs
  data/tags.yaml
  timesketch/lib/emojis.py
Labels: cla: yes

#1266 Moved pylint CI checks to run in tox
  .pylintrc
  .travis.yml
  run_tests.py
  test_requirements.txt
  timesketch/lib/analyzers/phishy_domains.py
  timesketch/lib/analyzers/sigma_tagger.py
  timesketch/lib/datastores/elastic.py
  tox.ini
Labels: cla: yes

#1293 Added update release script and updated versions
  api_client/python/timesketch_api_client/version.py
  config/dpkg/changelog
  importer_client/python/timesketch_import_client/version.py
  timesketch/version.py
  utils/update_release.sh
Labels: cla: yes

#1296 Changing the test_tool mocks to reflect recent changes in the analyzer interface
  test_tools/etc/timesketch/__init__.py
  test_tools/timesketch/lib/analyzers/interface.py
Labels: cla: yes

#1297 Update update_release.sh
  utils/update_release.sh
Labels: cla: yes

#1286 Sigma cleanup
  .gitignore
  data/linux/recon_commands.yaml
  data/linux/reverse_shell.yaml
  data/sigma/rules/lnx_susp_zenmap.yml
  data/sigma_config.yaml
  test_tools/test_events/README.md
  test_tools/test_events/sigma_events.jsonl
  timesketch/lib/analyzers/sigma_tagger.py
  timesketch/lib/analyzers/sigma_tagger_test.py
Labels: cla: yes

#1301 Update dependencies.ini
  dependencies.ini
Labels: cla: yes

#1302 Updated dpkg files
  config/dpkg/changelog
  config/dpkg/control
  config/dpkg/python3-timesketch.install
  dependencies.ini
Labels: cla: yes

#1304 Minor changes to test tools
  test_tools/timesketch/lib/analyzers/interface.py
  test_tools/timesketch/lib/analyzers/utils.py
Labels: cla: yes

#1308 Fix an issue with unicode chars in sigma rules
  timesketch/lib/analyzers/sigma_tagger.py
Labels: Bug, cla: yes

#1306 Adding analyzer_run.py documentation
  docs/WriteAnalyzers.md
Labels: cla: yes
