Repository google/timesketch, pull requests merged in 2020-03, with the labels that each got.

#1118 Fix start of Elasticsearch
  docker/docker-compose.yml
Labels: cla: yes

#1120 Group share UI and spacing in timeline picker
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.75481154.js
  timesketch/frontend/dist/js/chunk-common.75481154.js.map
  timesketch/frontend/dist/js/chunk-common.ea56227b.js
  timesketch/frontend/dist/js/chunk-common.ea56227b.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/ShareForm.vue
  timesketch/frontend/src/components/Sketch/TimelinePicker.vue
Labels: Bug, UI/UX, cla: yes

#1121 Minor bug fix in the importer code and a change in the way return fields are handled in the API
  api_client/python/setup.py
  api_client/python/timesketch_api_client/importer.py
  timesketch/api/v1/resources.py
Labels: cla: yes

#1123 Adding a logger to sketch.explore as well as a cleanup of "filter" in sketch API
  api_client/python/setup.py
  api_client/python/timesketch_api_client/sketch.py
  timesketch/api/v1/resources.py
Labels: Code health, cla: yes

#1124 Changed how message string is constructed
  api_client/python/setup.py
  api_client/python/timesketch_api_client/importer.py
Labels: Code health, cla: yes

#1127 Replaces PASSWORD with PASSWORD_FILE (fixes #1126)
  docker/docker-entrypoint.sh
Labels: cla: yes

#1129 Stats on indices
  timesketch/api/v1/resources.py
  timesketch/api/v1/resources_test.py
  timesketch/frontend/dist/css/chunk-common.d99b6eab.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.ea56227b.js
  timesketch/frontend/dist/js/chunk-common.ea56227b.js.map
  timesketch/frontend/dist/js/chunk-common.f5d9bf3b.js
  timesketch/frontend/dist/js/chunk-common.f5d9bf3b.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
  timesketch/frontend/src/components/Sketch/TimelinePicker.vue
  timesketch/frontend/src/filters/CompactBytes.js
  timesketch/frontend/src/views/SketchExplore.vue
  timesketch/lib/testlib.py
Labels: New feature, UI/UX, cla: yes

#1130 Adding a check to see whether index has completed before running an analyzer
  timesketch/lib/analyzers/interface.py
Labels: cla: yes

#1131 Minor change to cache, caching client
  api_client/python/setup.py
  api_client/python/timesketch_api_client/sketch.py
Labels: cla: yes

#1133 Opening test files with codecs instead of default open.
  test_tools/timesketch/lib/analyzers/interface.py
Labels: cla: yes

#1111 Sketch Analyzer for Windows artefacts of application crashes
  timesketch/lib/analyzers/__init__.py
  timesketch/lib/analyzers/win_crash.py
  timesketch/lib/analyzers/win_crash_test.py
Labels: New feature, cla: yes

#1135 Fix for a flaky test with the win crash analyzer.
  timesketch/lib/analyzers/win_crash_test.py
Labels: Bug, cla: yes

#1134 Adding support for working with stories from the API client, as well as adding aggregation support in the backend
  api_client/python/setup.py
  api_client/python/timesketch_api_client/aggregation.py
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/importer_test.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/story.py
  api_client/python/timesketch_api_client/story_test.py
  api_client/python/timesketch_api_client/test_lib.py
  run_tests.py
  timesketch/api/v1/resources.py
  timesketch/lib/analyzers/interface.py
Labels: New feature, cla: yes

#1136 Upgrading the fake analyzer interface with latest interface changes.
  test_tools/timesketch/lib/analyzers/interface.py
Labels: cla: yes

#1137 bump requests version to 2.22.0
  requirements.txt
Labels: cla: yes

#1138 Adding the ability to add users or groups to the sketch ACL.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/sketch.py
Labels: New feature, cla: yes

#1140 Always show share button and collaborator list
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.b80c5d6f.js
  timesketch/frontend/dist/js/chunk-common.b80c5d6f.js.map
  timesketch/frontend/dist/js/chunk-common.bb78e3e3.js
  timesketch/frontend/dist/js/chunk-common.bb78e3e3.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/views/SketchOverview.vue
Labels: cla: yes

#1141 New analyzer that adds tag/emojis to events based on config.
  data/tags.yaml
  timesketch/api/v1/resources.py
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.64df950a.js
  timesketch/frontend/dist/js/chunk-common.64df950a.js.map
  timesketch/frontend/dist/js/chunk-common.b80c5d6f.js
  timesketch/frontend/dist/js/chunk-common.b80c5d6f.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/ViewList.vue
  timesketch/lib/analyzers/__init__.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/analyzers/tagger.py
  timesketch/lib/analyzers/tagger_test.py
  timesketch/migrations/versions/64c00337b9d1_.py
  timesketch/migrations/versions/6e69f2cfcac1_.py
  timesketch/models/sketch.py
Labels: cla: yes

#1142 Adding the ability to export stories.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/story.py
  requirements.txt
  timesketch/api/v1/resources.py
  timesketch/lib/stories/__init__.py
  timesketch/lib/stories/api_fetcher.py
  timesketch/lib/stories/interface.py
  timesketch/lib/stories/manager.py
  timesketch/lib/stories/manager_test.py
  timesketch/lib/stories/markdown.py
Labels: New feature, cla: yes

#1143 Add an analyzer status check into the sketch API client.
  api_client/python/timesketch_api_client/sketch.py
Labels: New feature, cla: yes

#1144 Fix a bug if there are no stories in a sketch and add properties to View
  api_client/python/setup.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/view.py
Labels: Bug, cla: yes

#1147 Support non-text fields in aggregations
  timesketch/lib/aggregators/bucket.py
  timesketch/lib/aggregators/interface.py
  timesketch/lib/aggregators/term.py
Labels: cla: yes
