Repository google/timesketch, pull requests merged in 2020-04, with the labels that each got.

#1158 Fix docker installation documentation link.
  README.md
Labels: cla: yes

#1146 Several changes in the API, API client and analyzer for further story support
  api_client/python/setup.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/story.py
  api_client/python/timesketch_api_client/view.py
  test_tools/timesketch/lib/analyzers/interface.py
  test_tools/timesketch/lib/analyzers/utils.py
  timesketch/api/v1/resources.py
  timesketch/lib/aggregators/__init__.py
  timesketch/lib/aggregators/bucket.py
  timesketch/lib/aggregators/feed.py
  timesketch/lib/aggregators/interface.py
  timesketch/lib/aggregators/manager.py
  timesketch/lib/aggregators/manager_test.py
  timesketch/lib/aggregators/term.py
  timesketch/lib/analyzers/browser_search.py
  timesketch/lib/analyzers/browser_timeframe.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/analyzers/manager.py
  timesketch/lib/analyzers/utils.py
  timesketch/lib/charts/__init__.py
  timesketch/lib/charts/circle.py
  timesketch/lib/stories/api_fetcher.py
  timesketch/lib/stories/interface.py
  timesketch/lib/stories/markdown.py
Labels: cla: yes

#1167 Add listing of groups and users
  timesketch/tsctl.py
Labels: cla: yes

#1169 Update installation and plaso documentation
  docs/EnablePlasoUpload.md
  docs/Installation.md
Labels: cla: yes

#1168 Fixing typo Installation re. libffi
  docs/Installation.md
Labels: cla: yes

#1122 debian package manager tweaks
  docker/Dockerfile
  docker/factory/development/Dockerfile
Labels: cla: yes

#1166 Adding aggregation groups
  api_client/python/setup.py
  api_client/python/timesketch_api_client/aggregation.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/story.py
  timesketch/api/v1/resources.py
  timesketch/api/v1/routes.py
  timesketch/lib/aggregators/feed.py
  timesketch/lib/aggregators/interface.py
  timesketch/lib/analyzers/browser_timeframe.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/charts/barchart.py
  timesketch/lib/charts/interface.py
  timesketch/migrations/versions/58754b577173_.py
  timesketch/models/sketch.py
  timesketch/models/user.py
Labels: cla: no

#1172 Added ability to modify aggregations and aggregation groups
  api_client/python/setup.py
  api_client/python/timesketch_api_client/aggregation.py
  api_client/python/timesketch_api_client/sketch.py
  timesketch/api/v1/resources.py
Labels: cla: yes

#1176 Adding labels to aggregations, adding ability to filter based on labels.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/aggregation.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/story.py
  notebooks/jupyter-timesketch-demo.ipynb
  test_tools/timesketch/lib/analyzers/interface.py
  timesketch/api/v1/resources.py
  timesketch/lib/analyzers/browser_search.py
  timesketch/lib/analyzers/browser_timeframe.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/forms.py
  timesketch/models/annotations.py
  timesketch/models/sketch.py
Labels: Code health, New feature, cla: yes

#1178 Bugfix: Collaborator list and failed timelines
  timesketch/frontend/dist/css/chunk-common.9a64f96e.css
  timesketch/frontend/dist/css/chunk-vendors.6cc40e54.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.452fbdb7.js
  timesketch/frontend/dist/js/chunk-common.452fbdb7.js.map
  timesketch/frontend/dist/js/chunk-common.4e1cbb80.js
  timesketch/frontend/dist/js/chunk-common.4e1cbb80.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
  timesketch/frontend/src/views/SketchOverview.vue
Labels: cla: yes
