Repository google/timesketch, pull requests merged in 2020-01, with the labels that each got.

#1074 Fix context query bug
  timesketch/frontend/dist/css/chunk-common.d4d85507.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.325dc5f5.js
  timesketch/frontend/dist/js/chunk-common.325dc5f5.js.map
  timesketch/frontend/dist/js/chunk-common.bcce33cd.js
  timesketch/frontend/dist/js/chunk-common.bcce33cd.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/EventListRow.vue
  timesketch/frontend/src/views/SketchExplore.vue
Labels: Bug

#1080 Remove Python2 support
  .travis.yml
  config/travis/install.sh
  config/travis/run_python2.sh
  config/travis/runtests.sh
  docs/Installation.md
  docs/Upgrading.md
Labels: Code health

#1085 Adding a tool to run analyzers without requiring TS to be installed (for dev/testing purposes)
  test_tools/analyzer_run.py
  test_tools/timesketch/lib/analyzers/interface.py
  test_tools/timesketch/lib/analyzers/manager.py
  test_tools/timesketch/lib/analyzers/utils.py
  test_tools/timesketch/lib/definitions.py
  test_tools/timesketch/lib/emojis.py
Labels: New feature
