Repository google/timesketch, pull requests merged in 2020-05, with the labels that each got.

#1183 Changed the importer, adding support for config files, etc
  importer_client/python/setup.py
  importer_client/python/timesketch_import_client/data/__init__.py
  importer_client/python/timesketch_import_client/data/formatter.yaml
  importer_client/python/timesketch_import_client/importer.py
  importer_client/python/timesketch_import_client/utils.py
  importer_client/python/tools/timesketch_importer.py
  timesketch/api/v1/resources.py
Labels: cla: yes

#1188 Minor change to fix error reporting in the API client.
  api_client/python/timesketch_api_client/sketch.py
Labels: Bug, cla: yes

#1189 Adding a config and a crypto module to the API client.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/config.py
  api_client/python/timesketch_api_client/config_test.py
  api_client/python/timesketch_api_client/crypto.py
  docs/APIConfigFile.md
  docs/UploadData.md
  importer_client/python/setup.py
  importer_client/python/timesketch_import_client/cli.py
  importer_client/python/tools/timesketch_importer.py
  requirements.txt
Labels: New feature, cla: yes

#1192 Adding a helper function into the config assistant to fill in missing details
  api_client/python/setup.py
  api_client/python/timesketch_api_client/cli_input.py
  api_client/python/timesketch_api_client/config.py
  api_client/python/timesketch_api_client/crypto.py
  importer_client/python/setup.py
  importer_client/python/tools/timesketch_importer.py
Labels: New feature, cla: yes

#1193 Changed the `get_client` helper function inside the config library (API client)
  api_client/python/setup.py
  api_client/python/timesketch_api_client/config.py
  api_client/python/timesketch_api_client/crypto.py
Labels: Code health, cla: yes

#1196 Remove $ from the README.md
  docker/development/README.md
Labels: cla: yes

#1194 Splitting credentials out of crypto storage module in API client.
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/config.py
  api_client/python/timesketch_api_client/credentials.py
  api_client/python/timesketch_api_client/crypto.py
  importer_client/python/tools/timesketch_importer.py
Labels: cla: yes

#1207 Refactor Docker for Development and e2e tests
  docker/Dockerfile
  docker/build/Dockerfile-dev
  docker/build/Dockerfile-prod
  docker/build/README.md
  docker/build/cloudbuild.yaml
  docker/dev/Dockerfile
  docker/dev/README.md
  docker/dev/docker-compose.yml
  docker/dev/docker-entrypoint.sh
  docker/e2e/Dockerfile
  docker/e2e/README.md
  docker/e2e/docker-compose.yml
  docker/e2e/docker-entrypoint.sh
  docker/prod/README.md
Labels: cla: yes

#1205 add support for FireEye HX .mans files
  api_client/python/timesketch_api_client/sketch.py
  config/dpkg/timesketch-server.timesketch.default
  contrib/timesketch-importer.sh
  data/timesketch.conf
  importer_client/python/timesketch_import_client/importer.py
  importer_client/python/tools/timesketch_importer.py
  requirements.txt
  timesketch/frontend/src/views/SketchManageTimelines.vue
  timesketch/frontend/src/views/SketchOverview.vue
  timesketch/lib/tasks.py
  timesketch/templates/sketch/timelines.html
  timesketch/tsctl.py
Labels: cla: yes

#1212 Added missing tabulate dependency to dpkg files
  config/dpkg/changelog
  config/dpkg/control
  config/dpkg/python3-timesketch.install
Labels: cla: yes

#1209 Updated installation instructions
  docs/Installation.md
Labels: cla: yes

#1208 Adding HTML export to stories
  api_client/python/setup.py
  api_client/python/timesketch_api_client/story.py
  config/dpkg/changelog
  config/dpkg/control
  requirements.txt
  timesketch/api/v1/resources.py
  timesketch/lib/stories/__init__.py
  timesketch/lib/stories/api_fetcher.py
  timesketch/lib/stories/html.py
  timesketch/lib/stories/interface.py
  timesketch/lib/stories/markdown.py
Labels: New feature, cla: yes

#1224 Changed setup.py to not use pip internal-only API
  setup.py
Labels: cla: yes

#1225 Additional changes to setup.py to support older versions of setuptools
  setup.py
Labels: cla: yes

#1220 Added Ubuntu 20.04 Python 3.8 Travis CI tests
  .travis.yml
  config/travis/install.sh
  config/travis/run_python3.sh
  config/travis/runtests.sh
Labels: cla: yes

#1215 Adding an analyzer result object to API client.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/analyzer.py
  api_client/python/timesketch_api_client/error.py
  api_client/python/timesketch_api_client/sketch.py
  timesketch/api/v1/resources.py
Labels: cla: yes

#1222 Updated dependencies and test scripts
  .travis.yml
  MANIFEST.in
  config/dpkg/control
  config/dpkg/rules
  config/linux/gift_ppa_install.sh
  config/travis/install.sh
  config/travis/run_python3.sh
  config/travis/run_with_timeout.sh
  config/travis/runtests.sh
  dependencies.ini
  requirements.txt
  setup.py
  test_dependencies.ini
  test_requirements.txt
  tox.ini
Labels: cla: yes

#1227 Disable mans import task
  api_client/python/timesketch_api_client/sketch.py
  config/dpkg/timesketch-server.timesketch.default
  contrib/timesketch-importer.sh
  importer_client/python/timesketch_import_client/importer.py
  importer_client/python/tools/timesketch_importer.py
  requirements.txt
  timesketch/frontend/src/views/SketchManageTimelines.vue
  timesketch/frontend/src/views/SketchOverview.vue
  timesketch/lib/tasks.py
  timesketch/tsctl.py
Labels: cla: yes

#1228 Update Docker-dev Readme
  docker/dev/README.md
Labels: cla: yes

#1229 Added an import helper for reading configs.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/analyzer.py
  api_client/python/timesketch_api_client/sketch.py
  importer_client/python/setup.py
  importer_client/python/timesketch_import_client/data/__init__.py
  importer_client/python/timesketch_import_client/helper.py
  importer_client/python/timesketch_import_client/importer.py
  importer_client/python/timesketch_import_client/utils.py
  importer_client/python/tools/timesketch_importer.py
  timesketch/__init__.py
Labels: cla: yes

#1232 Added CI test for building Dockerfile-prod
  .travis.yml
  config/travis/runtests.sh
Labels: cla: yes

#1235 Adding the ability to create a view through the API client.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/sketch.py
Labels: New feature, cla: yes

#1236 Update docker dev README with right image
  docker/dev/README.md
Labels: cla: yes

#1237 Added CI tests for Ubuntu 20.04 with GIFT PPA
  .travis.yml
Labels: cla: yes

#1240 Minor bug fixes in the sketch API client library.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/sketch.py
Labels: Bug, cla: yes

#1241 Updated Linux installation script
  config/linux/gift_ppa_install.sh
  config/linux/ubuntu_install_timesketch.sh
Labels: cla: yes

#1233 Update Dockerfile-prod to install Timesketch from GIFT PPA
  docker/build/Dockerfile-prod
Labels: cla: yes

#1242 Adding the ability to add tags to events.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/sketch.py
  timesketch/api/v1/resources.py
  timesketch/api/v1/routes.py
Labels: cla: yes

#1177 Change the behavior of the Yeti analyzer
  timesketch/lib/analyzers/yetiindicators.py
  timesketch/lib/analyzers/yetiindicators_test.py
  timesketch/lib/testlib.py
Labels: cla: yes
