Repository google/timesketch, pull requests merged in 2020-06, with the labels that each got.

#1181 Archive sketch functionality
  api_client/python/setup.py
  api_client/python/timesketch_api_client/error.py
  api_client/python/timesketch_api_client/index.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/timeline.py
  data/timesketch.conf
  importer_client/python/timesketch_import_client/helper_test.py
  timesketch/api/v1/resources.py
  timesketch/api/v1/routes.py
  timesketch/lib/analyzers/yetiindicators_test.py
  timesketch/models/annotations.py
Labels: New feature, cla: yes

#1246 Adding the ability to export sketches in the API client
  api_client/python/timesketch_api_client/sketch.py
  timesketch/api/v1/resources.py
Labels: cla: yes

#1249 Fix Docker Readme link (fixes #1247)
  README.md
Labels: cla: yes

#1250 Splitting the Archive API calls to a separate file.
  timesketch/api/v1/archive.py
  timesketch/api/v1/resources.py
  timesketch/api/v1/routes.py
  timesketch/api/v1/utils.py
Labels: Code health, cla: yes

#1255 Hot patching the timesketch __init__ file until a new plaso release comes out
  timesketch/__init__.py
Labels: cla: yes

#1256 UI: Enable archive and export
  timesketch/frontend/dist/css/chunk-common.6dddd19d.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.62b97d5c.js
  timesketch/frontend/dist/js/chunk-common.62b97d5c.js.map
  timesketch/frontend/dist/js/chunk-common.74fc3a38.js
  timesketch/frontend/dist/js/chunk-common.74fc3a38.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/utils/RestApiClient.js
  timesketch/frontend/src/views/Sketch.vue
  timesketch/frontend/src/views/SketchOverview.vue
  timesketch/models/sketch.py
Labels: cla: yes

#1251 Refactor archive API as well as expanding export support
  timesketch/api/v1/archive.py
  timesketch/api/v1/resources.py
  timesketch/api/v1/utils.py
Labels: cla: yes

#1257 Fixing an issue in the event tagging API call.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/sketch.py
Labels: cla: yes

#1264 Refactor API
  timesketch/api/v1/resources.py
  timesketch/api/v1/resources/__init__.py
  timesketch/api/v1/resources/aggregation.py
  timesketch/api/v1/resources/analysis.py
  timesketch/api/v1/resources/archive.py
  timesketch/api/v1/resources/event.py
  timesketch/api/v1/resources/explore.py
  timesketch/api/v1/resources/searchindex.py
  timesketch/api/v1/resources/searchtemplate.py
  timesketch/api/v1/resources/session.py
  timesketch/api/v1/resources/sketch.py
  timesketch/api/v1/resources/story.py
  timesketch/api/v1/resources/task.py
  timesketch/api/v1/resources/timeline.py
  timesketch/api/v1/resources/upload.py
  timesketch/api/v1/resources/user.py
  timesketch/api/v1/resources/view.py
  timesketch/api/v1/resources_test.py
  timesketch/api/v1/routes.py
  timesketch/app.py
Labels: Code health, cla: yes

#1261 Improving error messages in the API client.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/aggregation.py
  api_client/python/timesketch_api_client/analyzer.py
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/error.py
  api_client/python/timesketch_api_client/index.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/story.py
  api_client/python/timesketch_api_client/timeline.py
Labels: Code health, cla: yes

#1252 Pinned pylint to version 2.4.x and addressed linter issues
  importer_client/python/timesketch_import_client/utils.py
  test_requirements.txt
  timesketch/__init__.py
  timesketch/api/v1/resources/archive.py
  timesketch/api/v1/utils.py
  timesketch/app.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/analyzers/manager_test.py
  timesketch/lib/analyzers/phishy_domains_test.py
  timesketch/lib/analyzers/utils.py
  timesketch/lib/charts/manager_test.py
  timesketch/lib/google_auth.py
  timesketch/lib/tasks.py
  timesketch/models/sketch.py
  timesketch/tsctl.py
  timesketch/views/auth.py
Labels: cla: yes

#1258 Added pylint support to tox configuration
  tox.ini
Labels: cla: yes

#1253 Updated pytlint configuration file to version 2.4.x
  .pylintrc
Labels: cla: yes

#1265 Adding more granular ACL granting.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/error.py
  api_client/python/timesketch_api_client/index.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
  timesketch/api/v1/resources/__init__.py
  timesketch/api/v1/resources/archive.py
  timesketch/api/v1/resources/user.py
  timesketch/api/v1/resources/view.py
  timesketch/models/acl.py
Labels: cla: yes

#1267 Changing the behavior of the API calls for event tagging
  api_client/python/timesketch_api_client/error.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
  timesketch/api/v1/resources/__init__.py
  timesketch/api/v1/resources/event.py
  timesketch/lib/datastores/elastic.py
Labels: cla: yes

#1272 Various changes to tsctl and the API
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/error.py
  api_client/python/timesketch_api_client/index.py
  timesketch/api/v1/resources/event.py
  timesketch/api/v1/resources/information.py
  timesketch/api/v1/resources/searchindex.py
  timesketch/api/v1/resources/sketch.py
  timesketch/api/v1/resources/task.py
  timesketch/api/v1/resources/timeline.py
  timesketch/api/v1/resources/user.py
  timesketch/api/v1/routes.py
  timesketch/lib/datastores/elastic.py
  timesketch/lib/tasks.py
  timesketch/tsctl.py
Labels: Bug, cla: yes

#1276 Fix method docstring (copy paste error)
  timesketch/api/v1/resources/information.py
Labels: cla: yes

#1275 Document location of frontend code on docker
  docs/Developers-Guide.md
Labels: cla: yes

#1277 Changed how manual events are added to a sketch.
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
  timesketch/api/v1/resources/event.py
  timesketch/lib/forms.py
Labels: cla: yes

#1245 Replace term whitelist with allowlist
  config/dpkg/timesketch-server.timesketch.default
  data/timesketch.conf
  timesketch/app.py
  timesketch/lib/analyzers/phishy_domains.py
  timesketch/views/auth.py
Labels: cla: yes

#1231 Add support for Sigma rules
  .gitignore
  README.md
  data/sigma_config.yaml
  docs/UseSigmaAnalyzer.md
  timesketch/lib/analyzers/sigma_tagger.py
  timesketch/lib/analyzers/utils.py
Labels: cla: yes

#1279 Bugfix: Set status on added timelines
  timesketch/api/v1/resources/timeline.py
Labels: cla: yes

#1281 Bugfix: Correct doc count for indices with >1 shard
  timesketch/api/v1/resources/sketch.py
Labels: cla: yes

#1284 Update screenshots
  docs/SketchOverview.md
  docs/images/2events.png
  docs/images/Import.png
  docs/images/Navigation.png
  docs/images/Sharingdialog.png
  docs/images/sharebutton.png
Labels: cla: yes
