Repository google/timesketch, pull requests merged in 2020-02, with the labels that each got.

#981 Psexec sessionizer
  timesketch/lib/analyzers/psexec_sessionizers.py
  timesketch/lib/analyzers/sequence_sessionizer_test.py
Labels: cla: yes

#980 Replace get event in tests
  timesketch/lib/analyzers/base_sessionizer_test.py
  timesketch/lib/analyzers/expert_sessionizers_test.py
  timesketch/lib/analyzers/sequence_sessionizer_test.py
  timesketch/lib/analyzers/sessionizer_test.py
  timesketch/lib/analyzers/ssh_sessionizer_test.py
  timesketch/lib/testlib.py
Labels: cla: yes

#1096 Fixing a minor issue if context is empty and some linter fixes
  test_tools/timesketch/lib/analyzers/interface.py
  test_tools/timesketch/lib/analyzers/utils.py
Labels: Bug, cla: yes

#976 Evtx sessionizer
  timesketch/lib/analyzers/evtx_sessionizers.py
  timesketch/lib/analyzers/evtx_sessionizers_test.py
  timesketch/lib/analyzers/sessionizer.py
  timesketch/lib/testlib.py
Labels: cla: yes

#972 SSH bruteforce session analyzer
  timesketch/lib/analyzers/base_sessionizer_test.py
  timesketch/lib/analyzers/expert_sessionizers.py
  timesketch/lib/analyzers/expert_sessionizers_test.py
  timesketch/lib/analyzers/sequence_sessionizer_test.py
  timesketch/lib/testlib.py
Labels: cla: yes

#1097 Bug fixes for tsctl
  timesketch/tsctl.py
Labels: Bug, cla: yes

#1098 Google Cloud Storage importer
  contrib/gcs_importer.py
Labels: cla: yes

#1095 Possibility to specify index when uploading data for the timesketch_api_client
  api_client/python/timesketch_api_client/importer.py
  api_client/python/timesketch_api_client/sketch.py
Labels: cla: yes

#1101 Changes to use pybuild debhelper
  config/dpkg/changelog
  config/dpkg/control
  config/dpkg/python-timesketch.install
  config/dpkg/rules
Labels: cla: yes

#1103 Changed setup.py to support bdist
  config/travis/runtests.sh
  setup.py
Labels: cla: yes

#1104 Updated l2tdevtools configuration and dpkg files
  config/dpkg/control
  dependencies.ini
  timesketch.ini
Labels: cla: yes

#1108 Elasticsearch 7.x support
  docker/development/docker-compose.yml
  docker/docker-compose.yml
  requirements.txt
  timesketch/api/v1/resources.py
  timesketch/lib/datastores/elastic.py
  timesketch/lib/tasks.py
Labels: cla: yes

#1099 Changed the upload API to support chunks and direct entries, added functionality into the importer
  api_client/python/setup.py
  api_client/python/timesketch_api_client/importer.py
  docs/UploadDataViaAPI.md
  timesketch/api/v1/resources.py
  timesketch/lib/errors.py
  timesketch/lib/forms.py
  timesketch/lib/tasks.py
  timesketch/lib/utils.py
  timesketch/tsctl.py
Labels: New feature, cla: yes

#1105 Added an importer tool as well as changing how jsonl files are imported using the importer
  api_client/python/setup.py
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/importer.py
  api_client/python/tools/timesketch_importer.py
  config/travis/install.sh
  docs/UploadData.md
Labels: New feature, cla: yes

#1113 Fix an issue with the importer
  api_client/python/setup.py
  api_client/python/timesketch_api_client/importer.py
  api_client/python/tools/timesketch_importer.py
  timesketch/lib/datastores/elastic.py
Labels: Bug, cla: yes

#1115 Better error UI
  timesketch/frontend/dist/css/chunk-common.bcebcc29.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.7039ab50.js
  timesketch/frontend/dist/js/chunk-common.7039ab50.js.map
  timesketch/frontend/dist/js/chunk-common.7b8530b6.js
  timesketch/frontend/dist/js/chunk-common.7b8530b6.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
  timesketch/frontend/src/views/SketchManageTimelines.vue
Labels: New feature, UI/UX, cla: yes

#1117 Minor changes to importer and api
  api_client/python/setup.py
  api_client/python/timesketch_api_client/importer.py
  timesketch/api/v1/resources.py
Labels: Bug, Code health, cla: yes
