Repository google/timesketch, pull requests merged in 2020-10, with the labels that each got.

#1380 fix typo
  docker/dev/README.md
  docs/UploadDataViaAPI.md
  docs/UseSigmaAnalyzer.md
  docs/Users-Guide.md
  notebooks/MUS2019_CTF.ipynb
  timesketch/lib/analyzers/browser_timeframe.py
Labels: cla: yes

#1384 Allow users to toggle time filters.
  timesketch/frontend/src/components/Sketch/EventListRowDetail.vue
  timesketch/frontend/src/components/Sketch/TimeFilter.vue
  timesketch/frontend/src/views/SketchExplore.vue
  timesketch/lib/datastores/elastic.py
Labels: UI/UX, cla: yes

#1379 New Saved Search UI
  timesketch/api/v1/resources/sketch.py
  timesketch/frontend/dist/css/chunk-common.5113155c.css
  timesketch/frontend/dist/css/chunk-common.bb928a33.css
  timesketch/frontend/dist/css/chunk-vendors.6cc40e54.css
  timesketch/frontend/dist/css/chunk-vendors.cf8d87c1.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.5765e29f.js
  timesketch/frontend/dist/js/chunk-common.5765e29f.js.map
  timesketch/frontend/dist/js/chunk-vendors.cdb9c224.js
  timesketch/frontend/dist/js/chunk-vendors.f65407b1.js
  timesketch/frontend/dist/login.html
  timesketch/frontend/package.json
  timesketch/frontend/src/assets/main.scss
  timesketch/frontend/src/components/Sketch/Aggregation.vue
  timesketch/frontend/src/components/Sketch/AnalyzerHistory.vue
  timesketch/frontend/src/components/Sketch/AnalyzerSessionDetail.vue
  timesketch/frontend/src/components/Sketch/CreateViewForm.vue
  timesketch/frontend/src/components/Sketch/EventListRow.vue
  timesketch/frontend/src/components/Sketch/StoryList.vue
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
  timesketch/frontend/src/components/Sketch/TimelinePicker.vue
  timesketch/frontend/src/components/Sketch/ViewList.vue
  timesketch/frontend/src/components/Sketch/ViewListDropdown.vue
  timesketch/frontend/src/main.js
  timesketch/frontend/src/utils/RestApiClient.js
  timesketch/frontend/src/views/Home.vue
  timesketch/frontend/src/views/SketchExplore.vue
  timesketch/frontend/src/views/SketchManageTimelines.vue
  timesketch/frontend/src/views/SketchOverview.vue
  timesketch/frontend/src/views/SketchStoryContent.vue
  timesketch/frontend/src/views/SketchStoryOverview.vue
Labels: cla: yes

#1385 new build
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.6147c3f1.js
  timesketch/frontend/dist/js/chunk-common.6147c3f1.js.map
  timesketch/frontend/dist/login.html
Labels: cla: yes

#1387 Handle missing chips in filter
  timesketch/models/sketch.py
Labels: cla: yes

#1389 Adding the ability to check your own permission to a sketch.
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
  timesketch/api/v1/resources/__init__.py
  timesketch/models/acl.py
Labels: cla: yes

#1390 Bugfix: Display chip as active
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.4d163f4d.js
  timesketch/frontend/dist/js/chunk-common.4d163f4d.js.map
  timesketch/frontend/dist/js/chunk-common.b00c5422.js
  timesketch/frontend/dist/js/chunk-common.b00c5422.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/views/SketchExplore.vue
Labels: cla: yes

#1394 fixed URL for Google Python Style Guide
  CONTRIBUTING.md
Labels: cla: yes

#1396 Adding in a manual vega spec aggregator
  timesketch/lib/aggregators/__init__.py
  timesketch/lib/aggregators/feed.py
  timesketch/lib/aggregators/vega.py
Labels: cla: yes

#1400 Update test for sketch model
  timesketch/models/sketch_test.py
Labels: cla: yes

#1403 Added support for optional keyword rdomain
  timesketch/lib/analyzers/ssh_sessionizer.py
Labels: cla: yes

#1401 Requirement.txt changed and added httmock==1.3.0 to test_requirements.txt
  requirements.txt
  test_requirements.txt
Labels: cla: yes

#1404 Manually add/filter labels
  timesketch/api/v1/resources/event.py
  timesketch/api/v1/resources/sketch.py
  timesketch/frontend/dist/css/chunk-common.7ab477bf.css
  timesketch/frontend/dist/css/chunk-common.dcf90296.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.c75ad5e8.js
  timesketch/frontend/dist/js/chunk-common.c75ad5e8.js.map
  timesketch/frontend/dist/js/chunk-common.e138a83d.js
  timesketch/frontend/dist/js/chunk-common.e138a83d.js.map
  timesketch/frontend/dist/js/chunk-vendors.7e6f512d.js
  timesketch/frontend/dist/js/chunk-vendors.f65407b1.js
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/assets/main.scss
  timesketch/frontend/src/components/Sketch/EventList.vue
  timesketch/frontend/src/components/Sketch/EventListRow.vue
  timesketch/frontend/src/components/Sketch/ViewListDropdown.vue
  timesketch/frontend/src/filters/FilterChip.js
  timesketch/frontend/src/filters/FormatTimestamp.js
  timesketch/frontend/src/main.js
  timesketch/frontend/src/utils/RestApiClient.js
  timesketch/frontend/src/views/SketchExplore.vue
  timesketch/frontend/src/views/SketchOverview.vue
  timesketch/lib/datastores/elastic.py
  timesketch/lib/forms.py
  timesketch/lib/testlib.py
Labels: New feature, cla: yes, javascript, python

#1405 Minor bug fixes here and there.
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
  requirements.txt
  timesketch/lib/stories/api_fetcher.py
Labels: cla: yes

#1407 Bugfix for label aggregation
  timesketch/lib/datastores/elastic.py
Labels: cla: yes

#1409 Add example to API client usage doc
  docs/APIClient.md
Labels: api_client, cla: yes

#1413 API client: Adding a check for scroll ID in the explore function
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
Labels: Bug, cla: yes

#1416 Updating the colab notebook for the demo server.
  notebooks/colab-timesketch-demo.ipynb
Labels: cla: yes

#1307 Verify Sigma Rules test tool
  data/sigma_config.yaml
  docs/UseSigmaAnalyzer.md
  test_tools/sigma_verify_rules.py
  test_tools/sigma_verify_rules_test.py
Labels: cla: yes

#1426 Fixes to the API and API client
  api_client/python/timesketch_api_client/timeline.py
  api_client/python/timesketch_api_client/version.py
  timesketch/api/v1/resources/analysis.py
  timesketch/api/v1/resources/timeline.py
  timesketch/api/v1/resources/upload.py
  timesketch/lib/forms.py
Labels: Bug, cla: yes

#1429 Added sketch attributes.
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
  data/ontology.yaml
  docker/dev/docker-entrypoint.sh
  docker/e2e/Dockerfile
  docs/Admin-Guide.md
  timesketch/api/v1/resources/analysis.py
  timesketch/api/v1/resources/attribute.py
  timesketch/api/v1/resources/explore.py
  timesketch/api/v1/resources/sketch.py
  timesketch/api/v1/routes.py
  timesketch/api/v1/utils.py
  timesketch/lib/datastores/elastic.py
  timesketch/lib/ontology.py
  timesketch/migrations/versions/fc7bc5c66c63_.py
  timesketch/models/sketch.py
Labels: Feature request, cla: yes

#1430 Adding the ability for analyzers to add sketch attributes
  test_tools/timesketch/lib/analyzers/interface.py
  timesketch/lib/analyzers/interface.py
Labels: cla: yes

#1431 Fix a bug in the API client
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
Labels: Bug, cla: yes

#1433 Stripping pagination from saved views.
  api_client/python/timesketch_api_client/story.py
  api_client/python/timesketch_api_client/version.py
  timesketch/api/v1/resources/view.py
Labels: Bug, cla: yes

#1437 Fix api docstring typo
  api_client/python/timesketch_api_client/sketch.py
Labels: cla: yes

#1425 Adding notebooks for solving the case of the stolen Szechuan sauce
  notebooks/Stolen_Szechuan_Sauce_Analysis.ipynb
  notebooks/Stolen_Szechuan_Sauce_Data_Upload.ipynb
  notebooks/colab-timesketch-demo.ipynb
Labels: cla: yes

#1436 Improve error handling in the get_client function of the config API client module
  api_client/python/timesketch_api_client/config.py
  api_client/python/timesketch_api_client/version.py
Labels: cla: yes
