Repository google/timesketch, pull requests merged in 2020-09, with the labels that each got.

#1356 Fix width on main screenshot
  README.md
Labels: cla: yes

#1357 Small update to the 'Show data types' button
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
Labels: UI/UX, cla: yes

#1358 Minor changes to the way date is parsed when a custom event is added
  api_client/python/timesketch_api_client/sketch.py
  timesketch/api/v1/resources/event.py
Labels: cla: yes

#1361 Adding `set_data_type` into the importer.
  importer_client/python/timesketch_import_client/importer.py
  importer_client/python/timesketch_import_client/version.py
Labels: cla: yes

#1359 New end-to-end testing framework
  .github/workflows/main.yml
  docker/e2e/Dockerfile
  docker/e2e/docker-compose.yml
  docker/e2e/docker-entrypoint.sh
  end_to_end_tests/__init__.py
  end_to_end_tests/interface.py
  end_to_end_tests/manager.py
  end_to_end_tests/query_test.py
  end_to_end_tests/test_data/evtx.plaso
  end_to_end_tests/tools/run_end_to_end_tests.sh
  end_to_end_tests/tools/run_in_container.py
Labels: cla: yes

#1364 Unarchive a sketch: User does not have sufficient access rights to delete a sketch.
  timesketch/api/v1/resources/archive.py
Labels: cla: yes

#1363 Adding the ability to define return fields in the search_by_label function.
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
Labels: cla: yes

#1366 Several fixes: workflow changed, size in query_filter is honored in API client, special types are stripped in uploads and bulk insert errors are surfaced
  .github/workflows/main.yml
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/timeline.py
  api_client/python/timesketch_api_client/timeline_test.py
  api_client/python/timesketch_api_client/version.py
  importer_client/python/timesketch_import_client/importer.py
  importer_client/python/timesketch_import_client/version.py
  timesketch/api/v1/resources/upload.py
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
  timesketch/lib/datastores/elastic.py
  timesketch/lib/tasks.py
  timesketch/lib/utils.py
Labels: cla: yes

#1355 Analyzer run description
  docs/WriteAnalyzers.md
  test_tools/analyzer_run.py
  timesketch/lib/analyzers/sigma_tagger.py
Labels: cla: yes

#1369 UI build
  timesketch/frontend/dist/css/chunk-common.70fbd895.css
  timesketch/frontend/dist/css/chunk-common.f84d44b3.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.8708b486.js
  timesketch/frontend/dist/js/chunk-common.8708b486.js.map
  timesketch/frontend/dist/js/chunk-common.e6772fca.js
  timesketch/frontend/dist/js/chunk-common.e6772fca.js.map
  timesketch/frontend/dist/js/chunk-vendors.740bb14a.js
  timesketch/frontend/dist/js/chunk-vendors.af0e1009.js
  timesketch/frontend/dist/login.html
Labels: cla: yes

#1367 Developer docs update
  docker/dev/README.md
  docs/Developers-Guide.md
Labels: cla: yes

#1372 Add button to remove story
  timesketch/frontend/src/components/Sketch/StoryList.vue
  timesketch/frontend/src/utils/RestApiClient.js
Labels: cla: yes

#1365 UI: Updating time filters
  timesketch/frontend/src/components/Sketch/TimeFilter.vue
  timesketch/frontend/src/views/SketchExplore.vue
Labels: UI/UX, cla: yes

#1374 Dark Mode
  timesketch/frontend/dist/css/chunk-common.5113155c.css
  timesketch/frontend/dist/css/chunk-common.70fbd895.css
  timesketch/frontend/dist/css/chunk-vendors.6cc40e54.css
  timesketch/frontend/dist/css/chunk-vendors.cf8d87c1.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.5765e29f.js
  timesketch/frontend/dist/js/chunk-common.5765e29f.js.map
  timesketch/frontend/dist/js/chunk-common.e6772fca.js
  timesketch/frontend/dist/js/chunk-common.e6772fca.js.map
  timesketch/frontend/dist/js/chunk-vendors.740bb14a.js
  timesketch/frontend/dist/js/chunk-vendors.cdb9c224.js
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/App.vue
  timesketch/frontend/src/assets/main.scss
  timesketch/frontend/src/components/AppNavbarMain.vue
  timesketch/frontend/src/components/Sketch/EventListRow.vue
  timesketch/frontend/src/components/Sketch/SketchSummary.vue
  timesketch/frontend/src/components/Sketch/StoryList.vue
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
  timesketch/frontend/src/components/Sketch/TimelinePicker.vue
  timesketch/frontend/src/views/Home.vue
  timesketch/frontend/src/views/SketchOverview.vue
  timesketch/frontend/src/views/SketchStoryContent.vue
Labels: cla: yes

#1375 Minor bug fixes
  timesketch/api/v1/resources/story.py
  timesketch/api/v1/resources/user.py
  timesketch/lib/utils.py
Labels: Bug, cla: yes

#1378 Update api doc
  docs/UploadDataViaAPI.md
Labels: Documentation, cla: yes
