Repository google/timesketch, pull requests merged in 2020-11, with the labels that each got.

#1443 Notebook update
  notebooks/Stolen_Szechuan_Sauce_Data_Upload.ipynb
Labels: cla: yes

#1445 APIClient doc link to Colab notebooks
  docs/APIClient.md
Labels: cla: yes

#1446 Remove sudo from the docker dev guide
  docker/dev/README.md
Labels: Documentation, cla: yes

#1444 Single event notebook
  notebooks/add_a_single_event_to_a_sketch.ipynb
Labels: cla: yes

#1447 Few updates to the MUS2019 CTF Colab notebook
  notebooks/MUS2019_CTF.ipynb
Labels: cla: yes

#1455 Updating the notebook for Szechuan sauce to use picatrix magics (and a minor bug fix in the API client)
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
  notebooks/Stolen_Szechuan_Sauce_Analysis.ipynb
Labels: cla: yes

#1457 Minor updates to the szechuan sauce analysis notebook
  notebooks/Stolen_Szechuan_Sauce_Analysis.ipynb
Labels: cla: yes

#1458 Docker refactor
  config/travis/runtests.sh
  contrib/deploy_timesketch.sh
  contrib/nginx.conf
  docker/build/README.md
  docker/build/cloudbuild.yaml
  docker/dev/build/Dockerfile
  docker/prod/README.md
  docker/release/README.md
  docker/release/build/Dockerfile-latest
  docker/release/build/Dockerfile-release
  docker/release/build/docker-entrypoint.sh
  docker/release/config.env
  docker/release/docker-compose.yml
  docs/Installation.md
Labels: cla: yes

#1459 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes

#1460 Update deploy_timesketch.sh
  contrib/deploy_timesketch.sh
Labels: cla: yes

#1461 Don't use scrolling for nested queries
  timesketch/lib/graphs/chrome_downloads.py
Labels: cla: yes

#1462 Graph fixes
  timesketch/api/v1/resources/graph.py
  timesketch/frontend/dist/css/chunk-common.8b6fa55f.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.28f27d76.js
  timesketch/frontend/dist/js/chunk-common.28f27d76.js.map
  timesketch/frontend/dist/js/chunk-common.394b0092.js
  timesketch/frontend/dist/js/chunk-common.394b0092.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/assets/main.scss
  timesketch/frontend/src/components/Sketch/Graph.vue
  timesketch/lib/graphs/chrome_downloads.py
  timesketch/lib/graphs/interface.py
  timesketch/lib/graphs/win_logins.py
  timesketch/lib/graphs/win_services.py
Labels: cla: yes

#1464 fix https://github.com/google/timesketch/issues/1450
  timesketch/lib/analyzers/interface.py
Labels: Bug, cla: yes

#1452 Analyzer feature extract
  data/features.yaml
  timesketch/lib/analyzers/feature_extraction.py
  timesketch/lib/analyzers/feature_extraction_test.py
Labels: cla: yes

#1463 API client changes: click removed from cli_input and adding aggregation into stories fixed.
  .travis.yml
  api_client/python/setup.py
  api_client/python/timesketch_api_client/aggregation.py
  api_client/python/timesketch_api_client/cli_input.py
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/config.py
  api_client/python/timesketch_api_client/story.py
  api_client/python/timesketch_api_client/version.py
  timesketch/lib/analyzers/feature_extraction.py
  timesketch/lib/analyzers/interface.py
Labels: cla: yes

#1466 Providing a long description to the API client package.
  api_client/python/setup.py
Labels: cla: yes

#1467 Update docker images to use Ubuntu 20.04
  config/travis/install.sh
  dependencies.ini
  docker/dev/Dockerfile
  docker/dev/build/Dockerfile
  docker/dev/build/docker-entrypoint.sh
  docker/dev/docker-compose.yml
  docker/e2e/Dockerfile
  docker/release/build/Dockerfile-latest
  requirements.txt
Labels: cla: yes

#1469 Fix a bug in the save function of the aggregation API object
  api_client/python/timesketch_api_client/aggregation.py
Labels: cla: yes

#1468 Fix issue 1465 by removing hacky string replace .keyword
  timesketch/lib/analyzers/sigma_tagger.py
Labels: cla: yes

#1471 Save and cache graphs
  timesketch/api/v1/resources/__init__.py
  timesketch/api/v1/resources/graph.py
  timesketch/api/v1/routes.py
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.394b0092.js
  timesketch/frontend/dist/js/chunk-common.394b0092.js.map
  timesketch/frontend/dist/js/chunk-common.d3e264fb.js
  timesketch/frontend/dist/js/chunk-common.d3e264fb.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/Graph.vue
  timesketch/frontend/src/utils/RestApiClient.js
  timesketch/lib/graphs/interface.py
  timesketch/migrations/versions/36e85b266dba_.py
  timesketch/migrations/versions/58754b577173_.py
  timesketch/migrations/versions/64c00337b9d1_.py
  timesketch/migrations/versions/654121a84a33_.py
  timesketch/migrations/versions/be32626451fb_.py
  timesketch/migrations/versions/c380f6dff0bd_.py
  timesketch/migrations/versions/ecf00882f546_.py
  timesketch/migrations/versions/fc7bc5c66c63_.py
  timesketch/models/__init__.py
  timesketch/models/sketch.py
Labels: cla: yes

#1474 Removed typing from story.py, which does not work on py3.6
  api_client/python/timesketch_api_client/story.py
  api_client/python/timesketch_api_client/version.py
Labels: cla: yes

#1475 Bug fix for winservices graph plugin
  timesketch/lib/graphs/win_services.py
Labels: cla: yes

#1476 Adding a GH workflow for unit tests
  .github/workflows/unittest-pipenv.yml
  .github/workflows/unittest-ppa.yml
  .travis.yml
  README.md
  tox.ini
Labels: cla: yes

#1478 Remove Travis in favour of GH actions
  config/linux/nginx.conf.example
  config/linux/systemd/celery.service
  config/linux/systemd/timesketch.service
  config/linux/systemd/timesketch.socket
  config/travis/install.sh
  config/travis/run_pylint.sh
  config/travis/run_python3.sh
  config/travis/run_with_timeout.sh
  config/travis/runtests.sh
Labels: cla: yes

#1480 Graph: Use ID from attributes
  timesketch/lib/graphs/interface.py
Labels: cla: yes

#1454 Improve the UX of Time Filters
  timesketch/frontend/src/components/Sketch/TimeFilter.vue
  timesketch/frontend/src/views/SketchExplore.vue
  timesketch/lib/datastores/elastic.py
Labels: New feature, UI/UX, cla: yes

#1483 Update GH actions
  .github/workflows/end-to-end.yml
  .github/workflows/unit-tests.yml
  .github/workflows/unittest-pipenv.yml
  end_to_end_tests/tools/run_end_to_end_tests.sh
Labels: cla: yes

#1484 Cleanup old travis related files
  config/linux/gift_ppa_install.sh
  config/linux/ubuntu_install_timesketch.sh
Labels: cla: yes

#1487 Updated dpkg configuration files
  config/dpkg/changelog
  config/dpkg/control
Labels: cla: yes

#1488 Adding a linter GH workflow and adding a bit more resiliency into the error logging in the ES datastore
  .github/workflows/linter.yml
  timesketch/lib/datastores/elastic.py
Labels: cla: yes

#1492 Pagination fixes
  timesketch/frontend/dist/css/chunk-common.53ea44ca.css
  timesketch/frontend/dist/css/chunk-common.8e081924.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.18111e2d.js
  timesketch/frontend/dist/js/chunk-common.18111e2d.js.map
  timesketch/frontend/dist/js/chunk-common.c1b4402b.js
  timesketch/frontend/dist/js/chunk-common.c1b4402b.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/views/SketchExplore.vue
Labels: Bug, cla: yes

#1494 Graph: Choose layout type and edge style
  timesketch/frontend/dist/css/chunk-common.7c30715d.css
  timesketch/frontend/dist/css/chunk-common.8e081924.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.c1b4402b.js
  timesketch/frontend/dist/js/chunk-common.c1b4402b.js.map
  timesketch/frontend/dist/js/chunk-common.c77a1acb.js
  timesketch/frontend/dist/js/chunk-common.c77a1acb.js.map
  timesketch/frontend/dist/js/chunk-vendors.3860ac12.js
  timesketch/frontend/dist/js/chunk-vendors.f0fb96a6.js
  timesketch/frontend/dist/login.html
  timesketch/frontend/package.json
  timesketch/frontend/src/assets/main.scss
  timesketch/frontend/src/components/Sketch/Graph.vue
Labels: Feature request, cla: yes
