Repository google/timesketch, pull requests merged in 2020-12, with the labels that each got.

#1497 Adding the ability to define multiple TS instances in the RC file.
  api_client/python/timesketch_api_client/config.py
  api_client/python/timesketch_api_client/crypto.py
Labels: cla: yes

#1490 Added API client search object
  .github/workflows/linter.yml
  api_client/python/timesketch_api_client/aggregation.py
  api_client/python/timesketch_api_client/analyzer.py
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/credentials.py
  api_client/python/timesketch_api_client/index.py
  api_client/python/timesketch_api_client/resource.py
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/search_test.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/sketch_test.py
  api_client/python/timesketch_api_client/story.py
  api_client/python/timesketch_api_client/test_lib.py
  api_client/python/timesketch_api_client/timeline.py
  api_client/python/timesketch_api_client/version.py
  api_client/python/timesketch_api_client/view.py
  api_client/python/timesketch_api_client/view_test.py
  docker/e2e/Dockerfile
  docs/APIClient.md
  end_to_end_tests/query_test.py
  timesketch/api/v1/resources/aggregation.py
  timesketch/api/v1/resources/view.py
  timesketch/lib/forms.py
Labels: cla: yes

#1498 Minor changes to the search API object.
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/timeline.py
Labels: cla: yes

#1456 Sigma API / api_client
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/sigma.py
  api_client/python/timesketch_api_client/sigma_test.py
  api_client/python/timesketch_api_client/test_lib.py
  data/timesketch.conf
  docker/dev/build/docker-entrypoint.sh
  docs/APIClient.md
  timesketch/api/v1/resources/sigma.py
  timesketch/api/v1/routes.py
  timesketch/lib/analyzers/sigma_tagger.py
  timesketch/lib/sigma_util.py
Labels: Experimental, New feature, api_client, cla: yes

#1500 Making minor changes to the search API client.
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/version.py
Labels: cla: yes

#1501 Making changes to example notebooks after an API update
  api_client/python/timesketch_api_client/aggregation.py
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/version.py
  notebooks/MUS2019_CTF.ipynb
  notebooks/Stolen_Szechuan_Sauce_Analysis.ipynb
  notebooks/colab-timesketch-demo.ipynb
  notebooks/jupyter-timesketch-demo.ipynb
Labels: cla: yes

#1503 Modification to enable connection to production Elastic instance
  data/timesketch.conf
  timesketch/lib/aggregators/interface.py
  timesketch/lib/datastores/elastic.py
  timesketch/lib/testlib.py
Labels: cla: yes

#1502 Sigma Rule maintain improvement
  test_tools/sigma_verify_rules.py
  timesketch/lib/sigma_util.py
Labels: Experimental, cla: yes

#1504 Adding picatrix docker container to the development docker config
  docker/dev/README.md
  docker/dev/build/Dockerfile-notebook
  docker/dev/build/snippets.json
  docker/dev/build/timesketch_token
  docker/dev/build/timesketchrc
  docker/dev/docker-compose.yml
Labels: cla: yes

#1505 Added support for config sections in importer and updated snippets in dev docker.
  docker/dev/build/10-widgets.py
  docker/dev/build/Dockerfile-notebook
  docker/dev/build/snippets.json
  docs/APIClient.md
  docs/APIConfigFile.md
  docs/Developers-Guide.md
  docs/images/colab_connected.png
  docs/images/colab_local_runtime.png
  docs/images/notebook_connect.png
  importer_client/python/timesketch_import_client/version.py
  importer_client/python/tools/timesketch_importer.py
Labels: cla: yes

#1506 Added a new snippet to display a button and a form to create a search query for TS.
  docker/dev/build/10-widgets.py
  docker/dev/build/Dockerfile-notebook
  docker/dev/build/snippets.json
Labels: cla: yes

#1507 Use docker network for picatrix notebook
  docker/dev/build/timesketchrc
  docker/dev/docker-compose.yml
Labels: cla: yes

#1510 Small fix for a bug in the search API client
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/version.py
Labels: cla: yes

#1508 Added missing credentials to documentation
  docs/Users-Guide.md
Labels: Documentation, cla: yes

#1513 Moving the run_analyzer from the sketch API Client to the timeline object.
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/timeline.py
  api_client/python/timesketch_api_client/version.py
  timesketch/api/v1/resources/archive.py
Labels: cla: yes

#1516 Tiny change to the API client
  api_client/python/timesketch_api_client/config.py
Labels: cla: yes

#1499 introcude troubleshooting guide
  docs/UseSigma.md
Labels: Documentation, cla: yes

#1517 [docs] How to run a single test file
  docs/Developers-Guide.md
Labels: Documentation, cla: yes

#1519 Customizing the notebook container
  docker/dev/build/Dockerfile-notebook
  docker/dev/build/custom.css
  docker/dev/build/logo.png
  docker/dev/build/timesketch/README.md
  docker/dev/build/timesketch/main.js
  docker/dev/build/timesketch/timesketch.yaml
Labels: cla: yes

#1520 Home overview and graph fixes
  timesketch/api/v1/resources/__init__.py
  timesketch/api/v1/resources/explore.py
  timesketch/api/v1/resources/sketch.py
  timesketch/frontend/dist/css/chunk-common.4fcecf97.css
  timesketch/frontend/dist/css/chunk-common.9007d817.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.95fe5cbc.js
  timesketch/frontend/dist/js/chunk-common.95fe5cbc.js.map
  timesketch/frontend/dist/js/chunk-common.feb2f739.js
  timesketch/frontend/dist/js/chunk-common.feb2f739.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/public/login.html
  timesketch/frontend/src/App.vue
  timesketch/frontend/src/assets/main.scss
  timesketch/frontend/src/components/AppNavbarMain.vue
  timesketch/frontend/src/components/Home/SketchList.vue
  timesketch/frontend/src/components/Sketch/Graph.vue
  timesketch/frontend/src/components/Sketch/GraphList.vue
  timesketch/frontend/src/components/Sketch/GraphPluginList.vue
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
  timesketch/frontend/src/utils/RestApiClient.js
  timesketch/frontend/src/views/Home.vue
  timesketch/frontend/src/views/Sketch.vue
  timesketch/frontend/src/views/SketchExplore.vue
  timesketch/frontend/src/views/SketchGraphExplore.vue
  timesketch/frontend/src/views/SketchGraphOverview.vue
  timesketch/frontend/src/views/SketchManageTimelines.vue
  timesketch/frontend/src/views/SketchManageViews.vue
  timesketch/frontend/src/views/SketchOverview.vue
  timesketch/frontend/src/views/SketchStoryContent.vue
  timesketch/frontend/src/views/SketchStoryOverview.vue
Labels: cla: yes

#1523 Require view name
  timesketch/api/v1/resources/view.py
Labels: cla: yes

#1524 Format graph elements suitable for networkx python lib
  timesketch/api/v1/resources/graph.py
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.f20d25b4.js
  timesketch/frontend/dist/js/chunk-common.f20d25b4.js.map
  timesketch/frontend/dist/js/chunk-common.f355ac60.js
  timesketch/frontend/dist/js/chunk-common.f355ac60.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/Graph.vue
  timesketch/frontend/src/utils/RestApiClient.js
Labels: cla: yes

#1522 Adding API client support for graphs.
  api_client/python/setup.py
  api_client/python/timesketch_api_client/graph.py
  api_client/python/timesketch_api_client/graph_test.py
  api_client/python/timesketch_api_client/sketch.py
  end_to_end_tests/__init__.py
  end_to_end_tests/graph_test.py
  end_to_end_tests/interface.py
  end_to_end_tests/tools/run_in_container.py
  timesketch/api/v1/resources/__init__.py
  timesketch/api/v1/resources/graph.py
Labels: cla: yes

#1529 [Sigma] improve evtx mapping
  data/sigma_config.yaml
Labels: cla: yes

#1528 Update Developers-Guide.md
  docs/Developers-Guide.md
  docs/images/kernel_restart.png
Labels: cla: yes

#1525 Sort dates correctly in the analyzer history view
  timesketch/frontend/src/components/Sketch/AnalyzerHistory.vue
Labels: cla: yes

#1538 Added last_activity of a sketch to the sketch meta section and into the API client
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
  timesketch/api/v1/resources/aggregation.py
  timesketch/api/v1/resources/explore.py
  timesketch/api/v1/resources/graph.py
  timesketch/api/v1/resources/sketch.py
  timesketch/api/v1/resources/story.py
  timesketch/api/v1/resources/timeline.py
  timesketch/api/v1/resources/upload.py
  timesketch/api/v1/resources/view.py
  timesketch/api/v1/utils.py
Labels: cla: yes

#1541 Added details to the current_user call in the API client and improving e2e tests
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/user.py
  api_client/python/timesketch_api_client/version.py
  end_to_end_tests/__init__.py
  end_to_end_tests/client_test.py
  end_to_end_tests/graph_test.py
  end_to_end_tests/interface.py
  end_to_end_tests/query_test.py
  timesketch/api/v1/resources/__init__.py
  timesketch/lib/datastores/elastic.py
Labels: cla: yes

#1545 Changes to dpkg configuration for Ubuntu 20.04
  config/dpkg/control
Labels: cla: yes
