Repository google/timesketch, pull requests merged in 2021-09, with the labels that each got.

#1939 Microseconds since epoch for JSONL input data
  timesketch/lib/utils.py
Labels: cla: yes, Bugfix

#1905 Fixes for read_and_validate_csv
  timesketch/lib/utils.py
Labels: cla: yes

#1941 Update plaso.mappings
  data/plaso.mappings
Labels: cla: yes

#1943 Bugfix for disappearing menubar
  timesketch/frontend/src/components/AppNavbarSecondary.vue
  timesketch/frontend/src/views/Attributes.vue
  timesketch/frontend/src/views/Intelligence.vue
Labels: cla: yes

#1947 initiatl sizing doc
  docs/getting-started/sizing.md
Labels: cla: yes

#1945 Docs and docstring to list_sketches API
  api_client/python/timesketch_api_client/client.py
  docs/developers/api-client.md
Labels: Documentation, cla: yes, API client

#1956 add GCP to sigma config file / mapping
  data/sigma_blocklist.csv
  data/sigma_config.yaml
Labels: cla: yes
