Repository google/timesketch, pull requests merged in 2021-06, with the labels that each got.

#1796 UI: Expose sketch attributes through a dynamic table display component
  timesketch/frontend/src/components/AppNavbarSecondary.vue
  timesketch/frontend/src/components/Common/TsDynamicTable.vue
  timesketch/frontend/src/router.js
  timesketch/frontend/src/views/Intelligence.vue
Labels: cla: yes

#1768 Added regular expressions into the tagging analyzer to provide more flexibility.
  data/tags.yaml
  timesketch/lib/analyzers/tagger.py
  timesketch/lib/utils.py
Labels: cla: yes

#1802 Add Youtube Channel and Twitter account to docs
  docs/community/resources.md
Labels: Documentation, cla: yes

#1799 Fix typo: encourage
  docs/getting-started/install.md
Labels: cla: yes

#1766 Updated Sigma tagging, few improvements
  data/sigma_blocklist.csv
  data/sigma_config.yaml
  data/timesketch.conf
  docs/learn/sigma.md
  notebooks/Sigma_test_Notebook.ipynb
  test_tools/sigma_verify_rules.py
  test_tools/sigma_verify_rules_test.py
  timesketch/lib/analyzers/sigma_tagger.py
  timesketch/lib/sigma_util.py
Labels: cla: yes

#1791 Added a data analyzer
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
  data/data_finder.yaml
  data/timesketch.conf
  docker/dev/build/docker-entrypoint.sh
  docker/e2e/Dockerfile
  docker/e2e/docker-entrypoint.sh
  end_to_end_tests/__init__.py
  end_to_end_tests/data_finder_test.py
  importer_client/python/timesketch_import_client/version.py
  importer_client/python/tools/timesketch_importer.py
  timesketch/api/v1/resources/datafinder.py
  timesketch/api/v1/routes.py
  timesketch/lib/analyzers/feature_extraction.py
  timesketch/lib/analyzers/tagger.py
  timesketch/lib/analyzers/utils.py
  timesketch/lib/analyzers/utils_test.py
  timesketch/lib/datafinder.py
  timesketch/lib/tasks.py
  timesketch/version.py
Labels: cla: yes

#1804 Sigma verify tool improv
  test_tools/sigma_verify_rules.py
Labels: Bug, cla: yes, sigma

#1806 Added a small logger statement in the importer client.
  importer_client/python/tools/timesketch_importer.py
Labels: cla: yes

#1809 Add additional regexes to extract IP addresses from sshd messages
  data/features.yaml
Labels: cla: yes

#1808 Update developer guide
  docs/developers/developer-guide.md
Labels: cla: yes

#1821 Fix bug in tagger analyzer
  timesketch/lib/analyzers/tagger.py
Labels: cla: yes

#1838 UI: Search autocomplete and dropdown
  data/generic.mappings
  timesketch/api/v1/resources/aggregation.py
  timesketch/api/v1/resources/explore.py
  timesketch/api/v1/routes.py
  timesketch/frontend/dist/css/chunk-common.7edc0083.css
  timesketch/frontend/dist/css/chunk-common.aea3f96f.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.86cbfb75.js
  timesketch/frontend/dist/js/chunk-common.86cbfb75.js.map
  timesketch/frontend/dist/js/chunk-common.88e98847.js
  timesketch/frontend/dist/js/chunk-common.88e98847.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/jsconfig.json
  timesketch/frontend/src/assets/main.scss
  timesketch/frontend/src/components/AppNavbarSecondary.vue
  timesketch/frontend/src/components/Common/ViewListCompact.vue
  timesketch/frontend/src/components/Explore/EventListRow.vue
  timesketch/frontend/src/components/Explore/SearchDropdown.vue
  timesketch/frontend/src/components/Explore/SearchHistoryTree.vue
  timesketch/frontend/src/components/Explore/SearchHistoryTreeNode.vue
  timesketch/frontend/src/components/Explore/TimeFilter.vue
  timesketch/frontend/src/main.js
  timesketch/frontend/src/store.js
  timesketch/frontend/src/utils/RestApiClient.js
  timesketch/frontend/src/views/Explore.vue
  timesketch/lib/aggregators/interface.py
  timesketch/lib/datastores/elastic.py
  timesketch/models/sketch.py
Labels: UI/UX, cla: yes

#1843 Fix to Time Filter Removal behavior
  timesketch/frontend/src/views/Explore.vue
Labels: Bug, UI/UX, cla: yes

#1847 Check for history node
  timesketch/api/v1/resources/explore.py
Labels: Bugfix, cla: yes

#1831 TsDynamicTable now has links pointing back to searches in sketch.
  timesketch/frontend/src/assets/main.scss
  timesketch/frontend/src/components/Common/TsDynamicTable.vue
Labels: cla: yes

#1857 Add intel from explore
  timesketch/frontend/package.json
  timesketch/frontend/src/assets/main.scss
  timesketch/frontend/src/components/Common/TsContextMenu.vue
  timesketch/frontend/src/components/Common/TsDynamicTable.vue
  timesketch/frontend/src/components/Common/TsIOCMenu.vue
  timesketch/frontend/src/components/Explore/EventListRowDetail.vue
  timesketch/frontend/src/views/Attributes.vue
  timesketch/frontend/src/views/Intelligence.vue
Labels: cla: yes

#1861 Extend SSH regex
  data/features.yaml
Labels: Bugfix, Small effort, cla: yes

#1862 UX local dev doc updates
  docs/developers/developer-guide.md
Labels: Documentation, cla: yes
