Repository google/timesketch, pull requests merged in 2021-07, with the labels that each got.

#1864 Remove capitalize from event list
  timesketch/frontend/src/components/Explore/EventList.vue
Labels: UI/UX, cla: yes

#1866 Fix formatting error in documentation
  docs/learn/create-timeline-from-json-csv.md
Labels: Documentation, cla: yes

#1845 Copy to clipboard for EventListRow and EvetlistRowDetail
  docs/learn/sketch-overview.md
  timesketch/frontend/package.json
  timesketch/frontend/src/components/Explore/EventListRow.vue
  timesketch/frontend/src/components/Explore/EventListRowDetail.vue
  timesketch/frontend/src/main.js
Labels: cla: yes

#1870 Mention WTF_CSRF_TIME_LIMIT in timesketch.conf
  data/timesketch.conf
Labels: Backend, Bugfix, Deployment, Documentation, cla: yes

#1865 Add sysadmin guide to the documentation
  docs/sysadmin/install.md
  docs/sysadmin/troubleshooting.md
  docs/sysadmin/tsctl.md
  docs/sysadmin/upgrade.md
Labels: Documentation, cla: yes

#1873 Update timesketch_importer.py
  importer_client/python/timesketch_import_client/version.py
  importer_client/python/tools/timesketch_importer.py
Labels: Importer client, cla: yes

#1882 Make access to intelligence attributes safer
  timesketch/frontend/src/components/Common/TsDynamicTable.vue
  timesketch/frontend/src/views/Intelligence.vue
Labels: cla: yes
