Repository google/timesketch, pull requests merged in 2021-01, with the labels that each got.

#1542 Various updates to the API Client
  api_client/python/timesketch_api_client/aggregation.py
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/timeline.py
  api_client/python/timesketch_api_client/version.py
  timesketch/api/v1/resources/__init__.py
  timesketch/api/v1/resources/aggregation.py
  timesketch/api/v1/resources/analysis.py
  timesketch/api/v1/resources/sketch.py
  timesketch/lib/google_auth.py
Labels: cla: yes

#1550 Update SearchQueryGuide views
  docs/SearchQueryGuide.md
Labels: Documentation, cla: yes

#1544 Fix remove_timeline_label() permission check
  timesketch/api/v1/resources/timeline.py
Labels: cla: yes

#1546 Changes to dpkg configuration for release
  config/dpkg/changelog
Labels: cla: yes

#1551 Adding additional sleep to e2e tests.
  end_to_end_tests/interface.py
Labels: cla: yes

#1552 Move stories to metadata
  timesketch/api/v1/resources/__init__.py
  timesketch/api/v1/resources/sketch.py
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.6e554ecc.js
  timesketch/frontend/dist/js/chunk-common.6e554ecc.js.map
  timesketch/frontend/dist/js/chunk-common.cb198678.js
  timesketch/frontend/dist/js/chunk-common.cb198678.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/StoryList.vue
  timesketch/frontend/src/views/SketchOverview.vue
  timesketch/frontend/src/views/SketchStoryOverview.vue
Labels: cla: yes

#1553 Bugfix: Handle system generated stories
  timesketch/api/v1/resources/sketch.py
Labels: Bug, cla: yes

#1557 Timesketch summit 2021
  docs/events/2021_timesketch_summit.md
Labels: Documentation, cla: yes

#1562 Changes to API and API client
  api_client/python/timesketch_api_client/analyzer.py
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/timeline.py
  api_client/python/timesketch_api_client/version.py
  docker/dev/build/docker-entrypoint.sh
  importer_client/python/timesketch_import_client/importer.py
  importer_client/python/timesketch_import_client/version.py
  requirements.txt
  timesketch/api/v1/resources/aggregation.py
  timesketch/api/v1/resources/timeline.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/analyzers/win_evtxgap.py
  timesketch/lib/datastores/elastic.py
  timesketch/lib/sigma_util.py
Labels: cla: yes

#1563 Added new IP address related feature extractors
  data/features.yaml
  timesketch/lib/analyzers/ssh_sessionizer.py
Labels: cla: yes

#1566 Minor API client changes
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
  timesketch/api/v1/resources/explore.py
  timesketch/lib/forms.py
Labels: cla: yes

#1565 First phase of new way of storing data in TS.
  api_client/python/timesketch_api_client/config.py
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/search_test.py
  api_client/python/timesketch_api_client/sketch.py
  importer_client/python/timesketch_import_client/importer.py
  importer_client/python/tools/timesketch_importer.py
  timesketch/api/v1/resources/explore.py
  timesketch/api/v1/resources/upload.py
  timesketch/lib/datastores/elastic.py
  timesketch/lib/tasks.py
  timesketch/lib/utils.py
  timesketch/lib/utils_test.py
  timesketch/models/sketch.py
  timesketch/models/sketch_test.py
Labels: cla: yes

#1571 corrects README doc link to Sigma
  README.md
Labels: cla: yes

#1572 hyphen error in readme
  README.md
Labels: cla: yes
