Repository google/timesketch, pull requests merged in 2021-02, with the labels that each got.

#1568 Adding datetime limits on the aggregation bucket.
  timesketch/api/v1/resources/aggregation.py
  timesketch/lib/aggregators/bucket.py
Labels: cla: yes

#1574 Changing __timeline_id to __ts_timeline_id and fixing build_query
  timesketch/api/v1/resources/event.py
  timesketch/api/v1/resources/sketch.py
  timesketch/frontend/src/components/Sketch/EventListRow.vue
  timesketch/frontend/src/views/SketchExplore.vue
  timesketch/lib/datastores/elastic.py
  timesketch/lib/definitions.py
  timesketch/lib/utils.py
Labels: cla: yes

#1569 Adding the ability to check whether a given index has __timeline_id in it.
  api_client/python/timesketch_api_client/index.py
  api_client/python/timesketch_api_client/version.py
  timesketch/api/v1/resources/searchindex.py
Labels: cla: yes

#1577 UI: Dedicated analysis tab
  api_client/python/timesketch_api_client/timeline.py
  timesketch/api/v1/resources/analysis.py
  timesketch/api/v1/resources/sketch.py
  timesketch/api/v1/routes.py
  timesketch/frontend/dist/css/chunk-common.f442a71a.css
  timesketch/frontend/dist/css/chunk-common.fa091c16.css
  timesketch/frontend/dist/css/chunk-vendors.329d9c7c.css
  timesketch/frontend/dist/css/chunk-vendors.5a1b1a38.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.8e017a32.js
  timesketch/frontend/dist/js/chunk-common.8e017a32.js.map
  timesketch/frontend/dist/js/chunk-common.ad91aebf.js
  timesketch/frontend/dist/js/chunk-common.ad91aebf.js.map
  timesketch/frontend/dist/js/chunk-vendors.53acc4a0.js
  timesketch/frontend/dist/js/chunk-vendors.98b8edc5.js
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/assets/main.scss
  timesketch/frontend/src/components/AppNavbarSecondary.vue
  timesketch/frontend/src/components/Sketch/ActiveAnalysisSessions.vue
  timesketch/frontend/src/components/Sketch/AnalyzerListDropdown.vue
  timesketch/frontend/src/components/Sketch/AnalyzerSessionDetail.vue
  timesketch/frontend/src/components/Sketch/TimelineList.vue
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
  timesketch/frontend/src/main.js
  timesketch/frontend/src/router.js
  timesketch/frontend/src/utils/RestApiClient.js
  timesketch/frontend/src/views/SketchAnalyzers.vue
  timesketch/frontend/src/views/SketchAnalyzersOverview.vue
  timesketch/frontend/src/views/SketchOverview.vue
  timesketch/lib/analyzers/account_finder.py
  timesketch/lib/analyzers/browser_search.py
  timesketch/lib/analyzers/browser_timeframe.py
  timesketch/lib/analyzers/chain.py
  timesketch/lib/analyzers/domain.py
  timesketch/lib/analyzers/expert_sessionizers.py
  timesketch/lib/analyzers/feature_extraction.py
  timesketch/lib/analyzers/gcp_servicekey.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/analyzers/login.py
  timesketch/lib/analyzers/ntfs_timestomp.py
  timesketch/lib/analyzers/phishy_domains.py
  timesketch/lib/analyzers/safebrowsing.py
  timesketch/lib/analyzers/sessionizer.py
  timesketch/lib/analyzers/sigma_tagger.py
  timesketch/lib/analyzers/similarity_scorer.py
  timesketch/lib/analyzers/ssh_sessionizer.py
  timesketch/lib/analyzers/tagger.py
  timesketch/lib/analyzers/win_crash.py
  timesketch/lib/analyzers/win_evtxgap.py
  timesketch/lib/analyzers/yetiindicators.py
  timesketch/lib/tasks.py
  timesketch/models/sketch.py
Labels: cla: yes

#1581 Simplified regex for IPv4 features
  data/features.yaml
Labels: cla: yes

#1582 Small bugfix in SSH features regex
  data/features.yaml
Labels: cla: yes

#1583 UI: Timeline tab and removing ability to add old indices to sketches
  timesketch/frontend/dist/css/chunk-common.530f1aec.css
  timesketch/frontend/dist/css/chunk-common.fa091c16.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.34015207.js
  timesketch/frontend/dist/js/chunk-common.34015207.js.map
  timesketch/frontend/dist/js/chunk-common.ad91aebf.js
  timesketch/frontend/dist/js/chunk-common.ad91aebf.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/AppNavbarSecondary.vue
  timesketch/frontend/src/components/Sketch/TimelineList.vue
  timesketch/frontend/src/utils/RestApiClient.js
  timesketch/frontend/src/views/SketchManageTimelines.vue
  timesketch/frontend/src/views/SketchManageViews.vue
Labels: cla: yes

#1578 Index Change: Changed plaso file ingestion, added query_dsl support and analyzer support
  data/plaso.mappings
  data/timesketch.conf
  docker/dev/build/docker-entrypoint.sh
  docker/e2e/Dockerfile
  docker/e2e/docker-entrypoint.sh
  requirements.txt
  timesketch/api/v1/resources/analysis.py
  timesketch/api/v1/resources/timeline.py
  timesketch/api/v1/resources/upload.py
  timesketch/api/v1/resources_test.py
  timesketch/lib/analyzers/account_finder.py
  timesketch/lib/analyzers/browser_search.py
  timesketch/lib/analyzers/browser_timeframe.py
  timesketch/lib/analyzers/chain.py
  timesketch/lib/analyzers/domain.py
  timesketch/lib/analyzers/feature_extraction.py
  timesketch/lib/analyzers/gcp_servicekey.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/analyzers/interface_test.py
  timesketch/lib/analyzers/login.py
  timesketch/lib/analyzers/ntfs_timestomp.py
  timesketch/lib/analyzers/phishy_domains.py
  timesketch/lib/analyzers/safebrowsing.py
  timesketch/lib/analyzers/similarity_scorer.py
  timesketch/lib/analyzers/tagger.py
  timesketch/lib/analyzers/win_crash.py
  timesketch/lib/analyzers/win_evtxgap.py
  timesketch/lib/analyzers/yetiindicators.py
  timesketch/lib/datastores/elastic.py
  timesketch/lib/tasks.py
  timesketch/lib/testlib.py
Labels: cla: yes

#1588 Adding timeline supports into aggregations.
  api_client/python/timesketch_api_client/sketch.py
  timesketch/api/v1/resources/aggregation.py
  timesketch/api/v1/resources/explore.py
  timesketch/lib/aggregators/bucket.py
  timesketch/lib/aggregators/interface.py
  timesketch/lib/aggregators/term.py
  timesketch/lib/analyzers/browser_search.py
  timesketch/lib/analyzers/feature_extraction.py
  timesketch/lib/analyzers/sigma_tagger.py
  timesketch/lib/analyzers/win_evtxgap.py
  timesketch/lib/utils.py
  timesketch/lib/utils_test.py
Labels: cla: yes

#1590 Updated e2e tests after plaso change and the run_plaso task to match and added timeline_id support to graphs
  api_client/python/timesketch_api_client/graph.py
  api_client/python/timesketch_api_client/version.py
  docker/e2e/Dockerfile
  end_to_end_tests/__init__.py
  end_to_end_tests/agg_test.py
  end_to_end_tests/client_test.py
  end_to_end_tests/test_data/evtx_part.csv
  timesketch/api/v1/resources/graph.py
  timesketch/lib/graphs/interface.py
  timesketch/lib/tasks.py
Labels: cla: yes

#1595 Moved docker configs to the dev GIFT PPA
  docker/dev/build/Dockerfile
  docker/e2e/Dockerfile
  docker/release/build/Dockerfile-latest
  docker/release/build/Dockerfile-release
  timesketch/lib/tasks.py
Labels: cla: yes

#1594 Deprecated the option to import timelines in tsctl.
  timesketch/tsctl.py
Labels: cla: yes

#1599 Fixed a minor issue with Docker files
  docker/release/build/Dockerfile-latest
  docker/release/build/Dockerfile-release
Labels: cla: yes

#1597 UI: Shifted filter buttons & added button titles
  timesketch/frontend/src/components/Sketch/EventListRow.vue
  timesketch/frontend/src/components/Sketch/EventListRowDetail.vue
Labels: UI/UX, cla: yes

#1601 Fixed #1600 by adding mappings to deployment script.
  contrib/deploy_timesketch.sh
  docs/Installation.md
Labels: cla: yes

#1605 Extract IP address from RdpCoreTS event logs
  data/features.yaml
Labels: cla: yes

#1606 Upgraded the importer version
  importer_client/python/timesketch_import_client/version.py
Labels: cla: yes

#1608 Add .venv to .gitignore
  .gitignore
Labels: cla: yes

#1613 Set correct timeline for analysis pipeline
  timesketch/frontend/dist/css/chunk-common.8b33fcb1.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.16dc2b1e.js
  timesketch/frontend/dist/js/chunk-common.16dc2b1e.js.map
  timesketch/frontend/dist/js/chunk-common.a0687acc.js
  timesketch/frontend/dist/js/chunk-common.a0687acc.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/AnalyzerSessionDetail.vue
  timesketch/lib/tasks.py
Labels: Bug, cla: yes

#1614 UI: Cleanup formatting
  timesketch/frontend/dist/css/chunk-common.3d969f36.css
  timesketch/frontend/dist/css/chunk-common.8b33fcb1.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.16dc2b1e.js
  timesketch/frontend/dist/js/chunk-common.16dc2b1e.js.map
  timesketch/frontend/dist/js/chunk-common.819b7364.js
  timesketch/frontend/dist/js/chunk-common.819b7364.js.map
  timesketch/frontend/dist/js/chunk-common.d0b437d0.js
  timesketch/frontend/dist/js/chunk-common.d0b437d0.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/AppNavbarMain.vue
  timesketch/frontend/src/components/Home/CreateSketchForm.vue
  timesketch/frontend/src/components/Home/SketchList.vue
  timesketch/frontend/src/components/Sketch/ActiveAnalysisSessions.vue
  timesketch/frontend/src/components/Sketch/AggregationCompact.vue
  timesketch/frontend/src/components/Sketch/AggregationGroupCompact.vue
  timesketch/frontend/src/components/Sketch/AggregationListDropdown.vue
  timesketch/frontend/src/components/Sketch/AggregatorListDropdown.vue
  timesketch/frontend/src/components/Sketch/AnalyzerHistory.vue
  timesketch/frontend/src/components/Sketch/AnalyzerSessionDetail.vue
  timesketch/frontend/src/components/Sketch/DynamicFormDatetimeInput.vue
  timesketch/frontend/src/components/Sketch/EventListCompact.vue
  timesketch/frontend/src/components/Sketch/EventListRow.vue
  timesketch/frontend/src/components/Sketch/EventListRowDetail.vue
  timesketch/frontend/src/components/Sketch/Graph.vue
  timesketch/frontend/src/components/Sketch/GraphList.vue
  timesketch/frontend/src/components/Sketch/GraphPluginList.vue
  timesketch/frontend/src/components/Sketch/SessionChart.vue
  timesketch/frontend/src/components/Sketch/ShareForm.vue
  timesketch/frontend/src/components/Sketch/TableChart.vue
  timesketch/frontend/src/components/Sketch/TimeFilter.vue
  timesketch/frontend/src/components/Sketch/TimelineList.vue
  timesketch/frontend/src/components/Sketch/TimelineListDropdown.vue
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
  timesketch/frontend/src/components/Sketch/TimelinePicker.vue
  timesketch/frontend/src/components/Sketch/UploadForm.vue
  timesketch/frontend/src/components/Sketch/VegaLiteChart.vue
  timesketch/frontend/src/components/Sketch/ViewListDropdown.vue
  timesketch/frontend/src/filters/FormatTimestamp.js
  timesketch/frontend/src/main.js
  timesketch/frontend/src/router.js
  timesketch/frontend/src/store.js
  timesketch/frontend/src/utils/RestApiClient.js
  timesketch/frontend/src/views/Home.vue
  timesketch/frontend/src/views/SketchAggregate.vue
  timesketch/frontend/src/views/SketchAnalyzersOverview.vue
  timesketch/frontend/src/views/SketchExplore.vue
  timesketch/frontend/src/views/SketchGraphExplore.vue
  timesketch/frontend/src/views/SketchGraphOverview.vue
  timesketch/frontend/src/views/SketchOverview.vue
  timesketch/frontend/src/views/SketchStory.vue
  timesketch/frontend/src/views/SketchStoryContent.vue
  timesketch/frontend/src/views/SketchStoryOverview.vue
  vetur.config.js
Labels: cla: yes

#1610 Fixed few issues: large text file imports, aggregations failing and upgrading PPA in docker files
  docker/dev/build/Dockerfile
  docker/e2e/Dockerfile
  docker/release/build/Dockerfile-latest
  docker/release/build/Dockerfile-release
  importer_client/python/timesketch_import_client/importer.py
  importer_client/python/timesketch_import_client/version.py
  timesketch/api/v1/resources/upload.py
  timesketch/lib/aggregators/feed.py
  timesketch/lib/aggregators/vega.py
Labels: cla: yes

#1616 Add ESLint GH action
  .github/workflows/linter.yml
Labels: cla: yes

#1623 Fixed issues with running analyzers in API client.
  api_client/python/timesketch_api_client/timeline.py
  api_client/python/timesketch_api_client/version.py
Labels: Bug, cla: yes

#1625 Minor bug fixes.
  importer_client/python/timesketch_import_client/importer.py
  importer_client/python/timesketch_import_client/version.py
  timesketch/api/v1/resources/timeline.py
  timesketch/api/v1/resources/upload.py
Labels: cla: yes

#1624 UI: Fix wrong timeline id in aggregations
  .github/workflows/linter.yml
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.046bd2b7.js
  timesketch/frontend/dist/js/chunk-common.046bd2b7.js.map
  timesketch/frontend/dist/js/chunk-common.d0b437d0.js
  timesketch/frontend/dist/js/chunk-common.d0b437d0.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/TimelineListDropdown.vue
  timesketch/frontend/src/views/SketchExplore.vue
Labels: cla: yes

#1626 Issue when removing timeline with a shared index
  timesketch/api/v1/resources/timeline.py
Labels: Bug, cla: yes

#1627 Added more error handling into the API, as well as retry to flushing events queue.
  timesketch/api/v1/resources/archive.py
  timesketch/api/v1/resources/explore.py
  timesketch/api/v1/resources/searchindex.py
  timesketch/api/v1/resources/sketch.py
  timesketch/api/v1/resources/timeline.py
  timesketch/api/v1/resources/upload.py
  timesketch/lib/aggregators/interface.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/datastores/elastic.py
  timesketch/lib/testlib.py
  timesketch/lib/utils.py
Labels: cla: yes

#1618 adding concepts and API dev guide
  docs/Developers-Guide.md
Labels: Documentation, cla: yes

#1628 Increased timeout value for bulk inserts by default, also made it configurable.
  data/timesketch.conf
  docker/dev/docker-compose.yml
  timesketch/api/v1/resources/explore.py
  timesketch/lib/datastores/elastic.py
Labels: Bug, New feature, cla: yes

#1631 Update docker-compose.yml
  docker/release/docker-compose.yml
Labels: cla: yes

#1632 Update ES version for release docker
  docker/release/config.env
Labels: cla: yes

#1635 Update pylint
  .pylintrc
Labels: cla: yes

#1636 Pinned pylint version
  .github/workflows/linter.yml
  .pylintrc
Labels: cla: yes

#1637 Pinned astroid to version 2.4.0 in linter action
  .github/workflows/linter.yml
Labels: cla: yes

#1634 Spelling in some files comments
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/config.py
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/sketch.py
  docs/Admin-Guide.md
  docs/CreateTimeLineFromOtherData.md
  docs/UseSigma.md
  importer_client/python/timesketch_import_client/importer.py
  test_tools/timesketch/lib/analyzers/interface.py
  timesketch/api/v1/resources/aggregation.py
  timesketch/api/v1/resources/sketch.py
  timesketch/lib/analyzers/feature_extraction.py
  timesketch/lib/analyzers/interface.py
  timesketch/lib/datastores/elastic.py
  timesketch/lib/sigma_util.py
Labels: cla: yes

#1638 Release 20210224
  config/dpkg/changelog
  timesketch/version.py
Labels: cla: yes

#1640 Added provider/context for uploads in the importer
  importer_client/python/timesketch_import_client/importer.py
  importer_client/python/timesketch_import_client/version.py
  timesketch/api/v1/resources/upload.py
Labels: cla: yes

#1644 Added provider/context to the CLI importer tool.
  importer_client/python/timesketch_import_client/version.py
  importer_client/python/tools/timesketch_importer.py
Labels: cla: yes

#1642 Added data source DB model
  timesketch/api/v1/resources/__init__.py
  timesketch/api/v1/resources/upload.py
  timesketch/frontend/dist/css/chunk-common.18a19126.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.046bd2b7.js
  timesketch/frontend/dist/js/chunk-common.046bd2b7.js.map
  timesketch/frontend/dist/js/chunk-common.bf1c1679.js
  timesketch/frontend/dist/js/chunk-common.bf1c1679.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
  timesketch/frontend/src/components/Sketch/UploadForm.vue
  timesketch/models/sketch.py
  timesketch/models/user.py
Labels: cla: yes

#1511 [API] introduce text --> sigma rule
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/sigma.py
  api_client/python/timesketch_api_client/sigma_test.py
  api_client/python/timesketch_api_client/test_lib.py
  test_tools/sigma_verify_rules.py
  timesketch/api/v1/resources/sigma.py
  timesketch/api/v1/resources_test.py
  timesketch/api/v1/routes.py
  timesketch/lib/sigma_util.py
  timesketch/lib/sigma_util_test.py
  timesketch/lib/testlib.py
Labels: api_client, cla: yes

#1534 Replace use of the csv library by pandas built-ins for data ingestion
  test_tools/test_events/sigma_events.csv
  timesketch/lib/utils.py
  timesketch/lib/utils_test.py
Labels: cla: yes

#1414 Added a Timesketch CLI client
  api_client/python/timesketch_api_client/config.py
  api_client/python/timesketch_api_client/config_test.py
  api_client/python/timesketch_api_client/sketch.py
  cli_client/python/setup.py
  cli_client/python/timesketch_cli_client/__init__.py
  cli_client/python/timesketch_cli_client/cli.py
  cli_client/python/timesketch_cli_client/commands/__init__.py
  cli_client/python/timesketch_cli_client/commands/analyze.py
  cli_client/python/timesketch_cli_client/commands/config.py
  cli_client/python/timesketch_cli_client/commands/importer.py
  cli_client/python/timesketch_cli_client/commands/search.py
  cli_client/python/timesketch_cli_client/commands/search_test.py
  cli_client/python/timesketch_cli_client/commands/sketch.py
  cli_client/python/timesketch_cli_client/commands/sketch_test.py
  cli_client/python/timesketch_cli_client/commands/timelines.py
  cli_client/python/timesketch_cli_client/commands/timelines_test.py
  cli_client/python/timesketch_cli_client/definitions.py
  cli_client/python/timesketch_cli_client/test_lib.py
  cli_client/python/timesketch_cli_client/version.py
  run_tests.py
Labels: cla: yes

#1646 Fixed couple of bugs in the sigma API and API Client
  api_client/python/timesketch_api_client/sigma.py
  timesketch/api/v1/resources/sigma.py
  timesketch/api/v1/resources_test.py
Labels: cla: yes

#1650 Docker: e2e / dev Sigma directory was not created before
  docker/dev/build/docker-entrypoint.sh
  docker/e2e/Dockerfile
Labels: Bug, cla: yes

#1645 Add the ability to use elasticsearch with SSL but without username/password authentication.
  timesketch/lib/datastores/elastic.py
Labels: cla: yes

#1651 Mention end2end tests in dev guide
  docs/Developers-Guide.md
Labels: Documentation, cla: yes

#1647 Another round of minor checks where unittests did not reflect the reality
  api_client/python/timesketch_api_client/sigma.py
  api_client/python/timesketch_api_client/test_lib.py
  timesketch/api/v1/resources/sigma.py
  timesketch/api/v1/resources_test.py
Labels: cla: yes

#1653 fixing some lint issues in the the e2e Docker readme file
  docker/e2e/README.md
Labels: Documentation, cla: yes
