Repository google/timesketch, pull requests merged in 2021-08, with the labels that each got.

#1886 Extended tsctl.py to add users to a sketch
  timesketch/tsctl.py
Labels: cla: yes, API client, Small effort

#1893 Bugfix for label filter
  timesketch/frontend/src/views/Explore.vue
Labels: cla: yes, Bugfix

#1879 Asynchronous update when adding timeline ID to events in bulk
  timesketch/api/v1/resources/event.py
Labels: cla: yes

#1842 UI: Vertical 3-dots on Timeline Chips
  timesketch/frontend/src/components/Analyze/AnalyzerHistory.vue
  timesketch/frontend/src/components/AppNavbarSecondary.vue
  timesketch/frontend/src/components/Explore/TimelineChip.vue
  timesketch/frontend/src/components/Explore/TimelinePicker.vue
  timesketch/frontend/src/router.js
  timesketch/frontend/src/store.js
  timesketch/frontend/src/views/Explore.vue
  timesketch/frontend/src/views/Overview.vue
Labels: UI/UX, cla: yes, Large effort, Frontend

#1888 GeoIP Analyzer
  data/timesketch.conf
  requirements.txt
  test_tools/timesketch/lib/emojis.py
  timesketch/lib/analyzers/__init__.py
  timesketch/lib/analyzers/geoip.py
  timesketch/lib/analyzers/geoip_test.py
  timesketch/lib/emojis.py
Labels: cla: yes

#1896 UI consistency
  timesketch/frontend/dist/css/chunk-common.7c53d079.css
  timesketch/frontend/dist/css/chunk-common.97d22b43.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.3e44cd88.js
  timesketch/frontend/dist/js/chunk-common.3e44cd88.js.map
  timesketch/frontend/dist/js/chunk-common.d7b13776.js
  timesketch/frontend/dist/js/chunk-common.d7b13776.js.map
  timesketch/frontend/dist/js/chunk-vendors.318574c2.js
  timesketch/frontend/dist/js/chunk-vendors.318574c2.js.map
  timesketch/frontend/dist/js/chunk-vendors.a6947d36.js
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/assets/main.scss
  timesketch/frontend/src/components/AppNavbarSecondary.vue
  timesketch/frontend/src/components/Common/CreateViewForm.vue
  timesketch/frontend/src/components/Common/Dropdown.vue
  timesketch/frontend/src/components/Explore/EventList.vue
  timesketch/frontend/src/components/Explore/EventListRow.vue
  timesketch/frontend/src/components/Explore/TimelineChip.vue
  timesketch/frontend/src/components/Explore/TimelinePicker.vue
  timesketch/frontend/src/components/Graph/Graph.vue
  timesketch/frontend/src/components/Timelines/TimelineList.vue
  timesketch/frontend/src/components/Timelines/TimelineListDropdown.vue
  timesketch/frontend/src/store.js
  timesketch/frontend/src/views/Explore.vue
  timesketch/frontend/src/views/Overview.vue
Labels: cla: yes

#1900 Bugfix: Highlight text shown twice
  timesketch/frontend/src/components/Explore/EventListRowDetail.vue
Labels: cla: yes, Bugfix

#1899 Geoip updates
  timesketch/lib/analyzers/geoip.py
Labels: cla: yes

#1906 1895 bugfix copy buttons
  timesketch/frontend/src/components/Explore/EventListRow.vue
  timesketch/frontend/src/components/Explore/EventListRowDetail.vue
Labels: UI/UX, cla: yes, Sigma, Small effort, Frontend, Bugfix

#1903 Introduce a Timesketch roadmap doc and Sigma
  docs/developers/roadmap.md
Labels: Documentation, cla: yes

#1909 ssh analyzer: Only create saved search if there are any sessions created
  timesketch/lib/analyzers/ssh_sessionizer.py
Labels: cla: yes, Bugfix

#1910 Fix: Sigma analyzer creates saved search and story even with 0 results
  timesketch/lib/analyzers/sigma_tagger.py
Labels: cla: yes

#1912 Remove mans from various docs
  .github/workflows/unit-tests.yml
  data/timesketch.conf
  importer_client/python/timesketch_import_client/importer.py
  timesketch/lib/tasks.py
Labels: cla: yes

#1904 Improve Sigma analyzer exception logging message
  timesketch/lib/analyzers/sigma_tagger.py
Labels: Code health, cla: yes, Sigma

#1917 Search history documentation
  docs/assets/videos/SearchHistory.mp4
  docs/learn/sketch-overview.md
Labels: cla: yes

#1914 Buttons for back/forward in search history
  timesketch/frontend/dist/css/chunk-common.061b487b.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.9eddbe21.js
  timesketch/frontend/dist/js/chunk-common.9eddbe21.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/assets/main.scss
  timesketch/frontend/src/components/Explore/SearchDropdown.vue
  timesketch/frontend/src/components/Explore/SearchHistoryButtons.vue
  timesketch/frontend/src/components/Explore/SearchHistoryTree.vue
  timesketch/frontend/src/views/Explore.vue
Labels: UI/UX, cla: yes, Small effort, Frontend

#1918 New build
  timesketch/frontend/dist/css/chunk-common.1a106c01.css
  timesketch/frontend/dist/js/chunk-common.ca7ede01.js
  timesketch/frontend/dist/js/chunk-common.ca7ede01.js.map
Labels: cla: yes

#1920 fix intel count
  timesketch/frontend/src/components/AppNavbarSecondary.vue
Labels: cla: yes

#1926 Corrected docstring in setup.py
  setup.py
Labels: cla: yes
