Repository google/timesketch, pull requests merged in 2021-11, with the labels that each got.

#2006 Update timesketch.conf
  data/timesketch.conf
Labels: cla: yes, Bugfix

#2002 More API client examples in the dev documentation
  docs/developers/api-client.md
Labels: cla: yes

#2008 Issue 1887 timefilters bug
  timesketch/frontend/src/components/Explore/TimeFilter.vue
Labels: UI/UX, cla: yes, Bugfix

#2014 fix csv of Sigma blocklist
  data/sigma_blocklist.csv
Labels: cla: yes

#2015 another missing column in sigma blocklist
  data/sigma_blocklist.csv
Labels: cla: yes

#2017 Fixed broken/outdated documentation URLs
  README.md
  docs/developers/analyzer-development.md
  docs/developers/api-upload-data.md
  docs/developers/getting-started.md
  docs/guides/admin/install.md
  docs/guides/getting-started.md
  docs/guides/user/import-from-json-csv.md
  docs/guides/user/upload-data.md
  mkdocs.yml
  timesketch/frontend/src/views/Overview.vue
Labels: cla: yes

#2013 add date search examples to search query guide
  docs/guides/user/search-query-guide.md
Labels: cla: yes

#1997 s/zenmap/zmap
  api_client/python/timesketch_api_client/sigma_test.py
  api_client/python/timesketch_api_client/test_lib.py
  contrib/deploy_timesketch.ps1
  contrib/deploy_timesketch.sh
  data/sigma/rules/lnx_susp_zmap.yml
  docs/developers/analyzer-development.md
  docs/developers/api-client.md
  docs/guides/user/sigma.md
  end_to_end_tests/client_test.py
  test_tools/sigma_verify_rules_test.py
  timesketch/api/v1/resources_test.py
  timesketch/lib/sigma_util_test.py
Labels: cla: yes

#1984 Create Intelligence Documentation
  docs/assets/images/add_intelligence.gif
  docs/guides/user/intelligence.md
  docs/guides/user/sketch-overview.md
  mkdocs.yml
Labels: cla: yes

#2020 Unrecognized attributes get the "other" type
  docs/guides/user/intelligence.md
  timesketch/frontend/src/components/Common/TsIOCMenu.vue
Labels: cla: yes

#2021 Add unit tests for frontend IOC guessing
  .github/workflows/unit-test-frontend.yml
  timesketch/frontend/src/components/Common/TsIOCMenu.vue
  timesketch/frontend/tests/unit/example.spec.js
  timesketch/frontend/tests/unit/iocmenu.spec.js
Labels: cla: yes

#2026 More efficient IOC searching
  timesketch/frontend/src/components/Common/TsIOCMenu.vue
  timesketch/frontend/src/components/Explore/EventListRowDetail.vue
  timesketch/frontend/tests/unit/iocmenu.spec.js
Labels: cla: yes

#2027 Generate graph for a specific timeline
  timesketch/frontend/src/components/Graph/Graph.vue
  timesketch/frontend/src/utils/RestApiClient.js
  timesketch/lib/graphs/interface.py
Labels: cla: yes

#2029 UI build
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.1df66615.js
  timesketch/frontend/dist/js/chunk-common.1df66615.js.map
  timesketch/frontend/dist/js/chunk-common.c8aa78cd.js
  timesketch/frontend/dist/js/chunk-common.c8aa78cd.js.map
  timesketch/frontend/dist/login.html
Labels: cla: yes

#2030 make it clear to which ID the timeline is uploaded
  importer_client/python/tools/timesketch_importer.py
Labels: cla: yes

#2036 Update sketch.py
  api_client/python/timesketch_api_client/sketch.py
Labels: cla: yes

#2042 Troubleshooting doc
  docs/guides/admin/troubleshooting.md
Labels: Documentation, cla: yes

#2040 how to scale ES
  docs/guides/admin/scaling-and-limits.md
Labels: Documentation, cla: yes

#1885 Delete and edit comments
  timesketch/api/v1/resources/__init__.py
  timesketch/api/v1/resources/event.py
  timesketch/frontend/src/components/Explore/EventListRow.vue
  timesketch/frontend/src/utils/RestApiClient.js
  timesketch/models/annotations.py
Labels: cla: yes

#2049 UI: Change the behavior of the "Star Toggle" button
  timesketch/frontend/src/components/Explore/EventListRow.vue
  timesketch/frontend/src/views/Explore.vue
Labels: Feature request, UI/UX, cla: yes, Small effort
