Repository google/timesketch, pull requests merged in 2021-03, with the labels that each got.

#1633 Bump sigmatools pypi version up
  dependencies.ini
  requirements.txt
Labels: cla: yes

#1643 Added search templates to API and API client
  api_client/python/timesketch_api_client/error.py
  api_client/python/timesketch_api_client/resource.py
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/timeline.py
  api_client/python/timesketch_api_client/version.py
  timesketch/api/v1/resources/searchtemplate.py
  timesketch/models/sketch.py
Labels: cla: yes

#1655 Forgot to include the `searchtemplate.py` file in the last PR
  api_client/python/timesketch_api_client/searchtemplate.py
Labels: cla: yes

#1611 Prometheus metric collection
  .github/workflows/unit-tests.yml
  config/dpkg/control
  data/gunicorn_config.py
  dependencies.ini
  docker/dev/docker-compose.yml
  docker/dev/grafana/dashboards/timesketch.json
  docker/dev/grafana/provisioning/dashboards/timesketch.yaml
  docker/dev/grafana/provisioning/datasources/prometheus.yaml
  docker/dev/prometheus/prometheus.yml
  docker/e2e/Dockerfile
  requirements.txt
  timesketch/api/v1/resources/analysis.py
  timesketch/lib/datastores/elastic.py
  timesketch/lib/definitions.py
  timesketch/wsgi.py
Labels: cla: yes

#1658 Update 2021_timesketch_summit.md
  docs/events/2021_timesketch_summit.md
Labels: Documentation, cla: yes

#1660 Add external talk to the agenda
  docs/events/2021_timesketch_summit.md
Labels: Documentation, cla: yes

#1662 Fixed limitations in file size in the data source model.
  docs/Admin-Guide.md
  timesketch/migrations/versions/41cae2c10cd7_.py
  timesketch/models/sketch.py
Labels: cla: yes

#1657 Cleaned up some of the API code.
  api_client/python/timesketch_api_client/index.py
  api_client/python/timesketch_api_client/sigma.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
Labels: cla: yes

#1664 Made slight changes to the API client and REST API.
  api_client/python/timesketch_api_client/config.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/version.py
  timesketch/api/v1/resources/timeline.py
  timesketch/api/v1/resources/upload.py
  timesketch/lib/tasks.py
  timesketch/models/acl.py
Labels: cla: yes

#1667 Added several enhancements to the importer and importer tasks.
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/version.py
  importer_client/python/timesketch_import_client/importer.py
  importer_client/python/timesketch_import_client/version.py
  importer_client/python/tools/timesketch_importer.py
  timesketch/api/v1/resources/task.py
  timesketch/api/v1/resources/timeline.py
  timesketch/api/v1/resources/upload.py
  timesketch/lib/tasks.py
  timesketch/lib/utils.py
  timesketch/version.py
Labels: cla: yes

#1675 Update 2021_timesketch_summit.md
  docs/events/2021_timesketch_summit.md
Labels: cla: yes

#1674 Fixed a bug in data ingestion
  timesketch/api/v1/resources/user.py
  timesketch/lib/datastores/elastic.py
Labels: cla: yes

#1676 Changed how we fill in NAN values while ingesting CSV files.
  timesketch/lib/datastores/elastic.py
  timesketch/lib/utils.py
Labels: cla: yes

#1678 Update installation/upgrading docs
  docs/CreateTimelineFromJSONorCSV.md
  docs/CreateTimelineFromPlaso.md
  docs/EnablePlasoUpload.md
  docs/Installation.md
  docs/Upgrading.md
  docs/UploadData.md
Labels: cla: yes

#1681 Added instructions on how to install a notebook container
  README.md
  docs/CreateTimeLineFromOtherData.md
  docs/Installation.md
  docs/Notebook.md
  docs/UploadData.md
  docs/Users-Guide.md
Labels: cla: yes

#1686 Minor bug fixes to the API client
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/story.py
  api_client/python/timesketch_api_client/version.py
Labels: Code health, cla: yes

#1680 Added a new documentation site
  .github/workflows/mkdocs.yml
  README.md
  docs/APIConfigFile.md
  docs/CNAME
  docs/Installation.md
  docs/assets/css/extra.css
  docs/assets/images/2events.png
  docs/assets/images/Import.png
  docs/assets/images/Navigation.png
  docs/assets/images/Newsketch.png
  docs/assets/images/Selection_005.png
  docs/assets/images/Sharingdialog.png
  docs/assets/images/SketchMore.png
  docs/assets/images/add_event.png
  docs/assets/images/colab_connected.png
  docs/assets/images/colab_local_runtime.png
  docs/assets/images/favicon.png
  docs/assets/images/filters.png
  docs/assets/images/heatmap.png
  docs/assets/images/kernel_restart.png
  docs/assets/images/notebook_connect.png
  docs/assets/images/readme.txt
  docs/assets/images/sharebutton.png
  docs/assets/images/singleevent.png
  docs/assets/images/timelinenavigation1.png
  docs/assets/images/timesketch-color.svg
  docs/assets/images/timesketch-white.svg
  docs/community/2021_timesketch_summit.md
  docs/community/resources.md
  docs/developers/analyzer-development.md
  docs/developers/api-client.md
  docs/developers/api-upload-data.md
  docs/developers/developer-guide.md
  docs/getting-started/install.md
  docs/getting-started/upload-data.md
  docs/index.md
  docs/learn/basic-concepts.md
  docs/learn/create-timeline-from-json-csv.md
  docs/learn/notebook.md
  docs/learn/search-query-guide.md
  docs/learn/server-admin.md
  docs/learn/sigma.md
  docs/learn/sketch-overview.md
  docs/learn/upgrade.md
  mkdocs.yml
Labels: cla: yes

#1688 Added a PR template.
  .github/ISSUE_TEMPLATE/support_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: cla: yes

#1689 Moved the PR template to a file instead of a folder.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#1691 Fixed few bugs in the API and alpha sorted saved searches
  timesketch/api/v1/resources/sketch.py
  timesketch/lib/datastores/elastic.py
  timesketch/lib/tasks.py
  timesketch/lib/utils.py
Labels: cla: yes

#1696 Fix broken links in README.md
  README.md
Labels: cla: yes

#1702 [Tiny fix] Updated link for Docker installation process
  docker/release/README.md
Labels: cla: yes

#1705 Update sigma.md
  docs/learn/sigma.md
Labels: Documentation, cla: yes, sigma

#1700 Changed how import errors are presented as well as ability to change passwords for the current user.
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/user.py
  api_client/python/timesketch_api_client/version.py
  docker/release/build/Dockerfile-release
  timesketch/api/v1/export.py
  timesketch/api/v1/resources/explore.py
  timesketch/api/v1/resources/upload.py
  timesketch/api/v1/resources/user.py
  timesketch/lib/tasks.py
  timesketch/migrations/versions/75af34d75b1e_extending_the_data_source_schema.py
  timesketch/models/sketch.py
  timesketch/version.py
Labels: cla: yes

#1710 Changed how ES object is created to support auth without ssl, as well as minor bug fix in analyzer selection.
  timesketch/lib/analyzers/manager.py
  timesketch/lib/analyzers/manager_test.py
  timesketch/lib/datastores/elastic.py
  timesketch/lib/tasks.py
Labels: cla: yes

#1712 Changed upload behavior when appending to an already existing timeline
  timesketch/api/v1/resources/upload.py
  timesketch/lib/tasks.py
Labels: cla: yes

#1714 UI: Quick typo fix, and change provider string from the importer library
  importer_client/python/timesketch_import_client/importer.py
  timesketch/frontend/dist/css/chunk-common.cc32c873.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.337de5f5.js
  timesketch/frontend/dist/js/chunk-common.337de5f5.js.map
  timesketch/frontend/dist/js/chunk-common.58130899.js
  timesketch/frontend/dist/js/chunk-common.58130899.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
Labels: cla: yes

#1719 UI: Remove old error field
  timesketch/frontend/dist/css/chunk-common.ba10a78e.css
  timesketch/frontend/dist/index.html
  timesketch/frontend/dist/js/chunk-common.58130899.js
  timesketch/frontend/dist/js/chunk-common.58130899.js.map
  timesketch/frontend/dist/js/chunk-common.a1241482.js
  timesketch/frontend/dist/js/chunk-common.a1241482.js.map
  timesketch/frontend/dist/login.html
  timesketch/frontend/src/components/Sketch/TimelineListItem.vue
Labels: cla: yes

#1718 Always uniq index lists
  timesketch/api/v1/resources/explore.py
  timesketch/api/v1/resources/sketch.py
  timesketch/lib/datastores/elastic.py
Labels: cla: yes

#1722 Added upper memory limits to psort.
  data/timesketch.conf
  timesketch/lib/tasks.py
Labels: cla: yes

#1717 Allow other OIDC providers for authentication
  data/timesketch.conf
  timesketch/lib/google_auth.py
Labels: cla: yes

#1725 Update developer-guide.md
  docs/developers/developer-guide.md
Labels: cla: yes
