Repository google/timesketch, pull requests merged in 2021-12, with the labels that each got.

#2055 Issue 1978: Fix limited list of Data Types
  timesketch/frontend/src/store.js
Labels: UI/UX, cla: yes, Small effort, Bugfix

#2063 Update import-from-json-csv.md
  docs/guides/user/import-from-json-csv.md
Labels: cla: yes

#2066 Change how memory dedicated to ES's JVM is calculated
  contrib/deploy_timesketch.sh
Labels: cla: yes

#2057 Expose Analyzer Logs in the Analyzers tab
  timesketch/frontend/src/components/Analyze/AnalyzerHistory.vue
  timesketch/frontend/src/components/Explore/TimelineChip.vue
  timesketch/frontend/src/components/Timelines/TimelineListItem.vue
  timesketch/frontend/src/views/Analyze.vue
Labels: Feature request, UI/UX, cla: yes, Small effort

#2038 Add incompatible Sigma rules to the blocklist
  contrib/deploy_timesketch.ps1
  contrib/deploy_timesketch.sh
  data/sigma_blocklist.csv
  data/timesketch.conf
  docker/dev/build/docker-entrypoint.sh
  docker/e2e/Dockerfile
  docs/guides/user/sigma.md
  timesketch/api/v1/resources/sigma.py
  timesketch/lib/sigma_util.py
  timesketch/lib/sigma_util_test.py
Labels: cla: yes

#2067 Add search examples to the documentation
  docs/guides/user/search-query-guide.md
Labels: cla: yes

#2070 Typo
  mkdocs.yml
Labels: cla: yes

#2085 Switch to OpenSearch for e2e tests
  .github/workflows/end-to-end.yml
  .github/workflows/linter.yml
  docker/e2e/docker-compose.yml
  end_to_end_tests/interface.py
  end_to_end_tests/tools/run_end_to_end_tests.sh
Labels: Code health, Deployment

#2086 Switch to OpenSearch for release docker
  contrib/deploy_timesketch.ps1
  docker/e2e/docker-compose.yml
  docker/e2e/docker-entrypoint.sh
  docker/release/config.env
  docker/release/docker-compose.yml
Labels: Code health, Deployment

#2089 Remove Elasticsearch from release docker config
  contrib/deploy_timesketch.ps1
  contrib/deploy_timesketch.sh
  docker/release/docker-compose.yml
Labels: Bugfix

#2045 Better intelligence view
  docs/assets/images/inteldemo.png
  docs/guides/user/intelligence.md
  timesketch/frontend/src/components/AppNavbarSecondary.vue
  timesketch/frontend/src/components/Common/TsIOCMenu.vue
  timesketch/frontend/src/components/Explore/EventListRowDetail.vue
  timesketch/frontend/src/utils/RestApiClient.js
  timesketch/frontend/src/views/Attributes.vue
  timesketch/frontend/src/views/Intelligence.vue
  timesketch/frontend/tests/unit/iocmenu.spec.js
Labels: cla: yes

#2069 Introduce delete user to tsctl.py
  docs/guides/admin/admin-cli.md
  timesketch/tsctl.py
Labels: cla: yes
