Repository google/timesketch, pull requests merged in 2022-10, with the labels that each got.

#2358 Changelog 2022-09
  docs/assets/images/2321_1.png
  docs/assets/images/2321_2.png
  docs/assets/images/2322_1.png
  docs/assets/images/2322_2.png
  docs/assets/images/2322_3.png
  docs/assets/images/2327.png
  docs/changelog/2022-09.md
  docs/index.md
Labels: Documentation

#2347 Modify Sigma analyzer / API Client / UX to use Database
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/sigma.py
  api_client/python/timesketch_api_client/sigma_test.py
  api_client/python/timesketch_api_client/version.py
  docs/developers/api-client.md
  docs/guides/analyzers/sigma_analyzer.md
  docs/guides/user/sigma.md
  end_to_end_tests/client_test.py
  notebooks/SigmaPortFileToDatabase.ipynb
  test_tools/sigma_verify_rules.py
  test_tools/sigma_verify_rules_test.py
  timesketch/api/v1/resources_test.py
  timesketch/frontend/src/components/Sigma/SigmaList.vue
  timesketch/frontend/src/utils/SigmaRuleTemplates.js
  timesketch/lib/analyzers/sigma_tagger.py
  timesketch/lib/analyzers/sigma_tagger_test.py
  timesketch/lib/sigma_util.py
  timesketch/lib/sigma_util_test.py
Labels: Sigma

#2372 Update docker images and CI tests to Ubuntu 22.04
  .github/workflows/e2e-tests.yml
  .github/workflows/linters.yml
  .github/workflows/unit-tests.yml
  docker/dev/build/Dockerfile
  docker/e2e/Dockerfile
  docker/release/build/Dockerfile-latest
  docker/release/build/Dockerfile-release
  requirements.txt
  run_tests.py
  test_requirements.txt
  timesketch/lib/analyzers/safebrowsing.py
Labels: Code health
