Repository google/timesketch, pull requests merged in 2022-08, with the labels that each got.

#2277 2276 feature extract doc
  docs/guides/analyzers/feature_extraction.md
Labels: Documentation

#2290 Fix redirect for OIDC logins
  timesketch/views/auth.py
Labels: Bugfix

#2296 Sigma rule database model + tests
  .gitignore
  timesketch/lib/testlib.py
  timesketch/models/sigma.py
  timesketch/models/sigma_test.py
Labels: Sigma
