Repository google/timesketch, pull requests merged in 2024-12, with the labels that each got.

#3245 Update SSH regex feature extraction
  data/regex_features.yaml
Labels: Analyzers

#3250 Resolve unsoundness caught by pytype --strict-none-binding.
  api_client/python/timesketch_api_client/aggregation.py
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/graph.py
Labels: API client

#3251 V3 update tsdev
  utils/tsdev.sh
Labels: Deployment
