Repository google/timesketch, pull requests merged in 2024-11, with the labels that each got.

#3231 Fix broken unit test workflows
  .github/workflows/unit-tests.yml
  run_tests.py
Labels: Bug

#3224 Aws cloudtrail tagger
  data/tags.yaml
Labels: Analyzers

#3214 Fix: Resolve pytype --strict-none-binding issue in the api client
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/story.py
Labels: API client

#3233 Provide actionable error message for complex search queries
  timesketch/frontend-ng/src/components/Explore/EventList.vue
  timesketch/lib/datastores/opensearch.py
Labels: Bug

#3235 ui build 20241129
  timesketch/frontend-ng/dist/index.html
  timesketch/frontend-ng/dist/js/index.1ff10a58.js
  timesketch/frontend-ng/dist/js/index.1ff10a58.js.map
  timesketch/frontend-ng/dist/js/index.fbd54591.js
  timesketch/frontend-ng/dist/js/index.fbd54591.js.map
Labels: Frontend
