Repository google/timesketch, pull requests merged in 2025-09, with the labels that each got.

#3510 fix: remove "version" from the toplevel from docker-compose files
  docker/dev/docker-compose.yml
  docker/e2e/docker-compose.yml
Labels: Code Health

#3511 feat: tscl improvements
  docs/guides/admin/admin-cli.md
  timesketch/lib/datastores/opensearch.py
  timesketch/tsctl.py
Labels: Backend, Code Health

#3517 feat: tsctl find-inconsistent-archives
  tests/test_events/mapping_limit_exceed.csv
  timesketch/tsctl.py
Labels: Backend, Code Health

#3515 refactor: s/prometheus_multiproc_dir/PROMETHEUS_MULTIPROC_DIR
  data/gunicorn_config.py
  docker/dev/docker-compose.yml
  timesketch/wsgi.py
Labels: Code Health

#3529 [Fix] Update Yeti certificate handling
  timesketch/api/v1/resources/scenarios.py
  timesketch/lib/analyzers/yetiindicators.py
Labels: Analyzers, Backend

#3532 fix: improve logging in aggregation.py
  timesketch/api/v1/resources/aggregation.py
Labels: Backend, Code Health

#3533 fix: improve error_handling in interface of e2e
  end_to_end_tests/interface.py
Labels: Backend, Code Health

#3528 feat(opensearch): Add support for custom CA certificates
  data/timesketch.conf
  timesketch/lib/datastores/opensearch.py
  timesketch/lib/tasks.py
Labels: Backend

#3537 fix: move pinfo earlier in the tasks check
  timesketch/lib/tasks.py
Labels: Code Health

#3538 fix: [API client] remove a warning in explore()
  api_client/python/timesketch_api_client/sketch.py
Labels: API client

#3431 [tsctl] Archive improvements
  docs/guides/user/sketch-overview.md
  timesketch/api/v1/resources/archive.py
  timesketch/frontend-ng/src/store.js
  timesketch/frontend-v3/src/stores/app.js
  timesketch/tsctl.py
Labels: Code Health

#3536 Support Sec-Gemini log analysis agent: Refactor log_analyzer feature & sec-gemini provider
  data/timesketch.conf
  docs/developers/log-analyzer-agent.md
  timesketch/frontend-v3/src/components/Investigation/Sidebar/QuestionsProgress.vue
  timesketch/lib/analyzers/llm_log_analyzer.py
  timesketch/lib/llms/features/log_analyzer.py
  timesketch/lib/llms/providers/secgemini_log_analyzer_agent.py
Labels: LLM
