Repository google/timesketch, pull requests merged in 2025-03, with the labels that each got.

#3312 [tests] add sketch related tests to the API unit tests
  setup.py
  timesketch/api/v1/resources_test.py
Labels: Code Health

#3314 frontend: LLM features switch to new llm endpoint
  timesketch/frontend-ng/src/components/Explore/EventList.vue
  timesketch/frontend-ng/src/components/Scenarios/QuestionCard.vue
Labels: Frontend, Code Health

#3313 Make suggested queries the active questions tab
  timesketch/frontend-ng/src/components/Scenarios/QuestionCard.vue
Labels: Frontend

#3318 Update nginx.conf
  contrib/nginx.conf
Labels: Deployment

#3319 UI build
  timesketch/frontend-ng/dist/index.html
  timesketch/frontend-ng/dist/js/index.29306127.js
  timesketch/frontend-ng/dist/js/index.29306127.js.map
  timesketch/frontend-ng/dist/js/index.32a7b878.js
  timesketch/frontend-ng/dist/js/index.32a7b878.js.map
  timesketch/frontend-v3/.eslintrc-auto-import.json
Labels: Frontend

#3322 Add instructions to load DFIQ templates to documentation
  docs/guides/admin/load-dfiq.md
  mkdocs.yml
Labels: Documentation

#3324 fix docstring for add_attribute in annotations.py
  timesketch/models/annotations.py
Labels: Code Health

#3323 Fix: Removal Logic Bug in Annotation Mixins
  timesketch/models/annotations.py
  timesketch/tsctl.py
Labels: Backend, Code Health

#3328 [tsclt] searchindex set get status
  docs/guides/admin/admin-cli.md
  timesketch/tsctl.py
Labels: CLI Client

#3316 adding unit tests for archiving a sketch
  timesketch/api/v1/resources_test.py
Labels: Backend, Code Health

#3336 Update api_client code for new pylint version
  api_client/python/timesketch_api_client/aggregation.py
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/config.py
  api_client/python/timesketch_api_client/config_test.py
  api_client/python/timesketch_api_client/crypto.py
  api_client/python/timesketch_api_client/graph.py
  api_client/python/timesketch_api_client/search.py
  api_client/python/timesketch_api_client/searchtemplate.py
  api_client/python/timesketch_api_client/sketch.py
  api_client/python/timesketch_api_client/story.py
  api_client/python/timesketch_api_client/timeline.py
Labels: API client, Code Health, python

#3339 Update importer client for new pylint config
  importer_client/python/timesketch_import_client/helper.py
  importer_client/python/timesketch_import_client/importer.py
Labels: Code Health, python

#3342 fix codespelling all over the project
  api_client/python/timesketch_api_client/scenario.py
  api_client/python/timesketch_api_client/search.py
  docs/changelog/index.md
  docs/guides/admin/load-dfiq.md
  docs/guides/admin/scaling-and-limits.md
  timesketch/api/v1/resources/event.py
  timesketch/api/v1/resources/scenarios.py
  timesketch/frontend-v3/src/components/UploadForm.vue
  timesketch/lib/analyzers/hashr_lookup.py
  timesketch/lib/analyzers/hashr_lookup_test.py
  timesketch/lib/analyzers/psexec_sessionizers.py
  timesketch/lib/analyzers/sequence_sessionizer.py
  timesketch/lib/analyzers/sequence_sessionizer_test.py
  timesketch/lib/analyzers/ssh_sessionizer_test.py
  timesketch/lib/llms/features/manager_test.py
  timesketch/lib/similarity.py
  timesketch/models/acl.py
Labels: Code Health

#3347 Prevent E2E / unit Tests on Documentation and Non-Code Changes
  .github/workflows/e2e-tests.yml
  .github/workflows/unit-tests.yml
Labels: Deployment, Code Health, github_actions

#3349 Remove sketch.upload() from the api client since it was unused and depracated for a long time
  api_client/python/timesketch_api_client/sketch.py
Labels: Code Health

#3353 Improve docstring of backend upload methd
  timesketch/api/v1/resources/upload.py
Labels: Code Health

#3241 Add Support for Searching Processing Timelines
  data/timesketch.conf
  timesketch/api/v1/resources/aggregation.py
  timesketch/api/v1/resources/event.py
  timesketch/api/v1/resources/explore.py
  timesketch/api/v1/resources/settings.py
  timesketch/api/v1/resources/user.py
  timesketch/api/v1/resources_test.py
  timesketch/frontend-ng/src/components/Analyzer/TimelineChip.vue
  timesketch/frontend-ng/src/components/Analyzer/TimelineSearch.vue
  timesketch/frontend-ng/src/components/Explore/AggregateDialog.vue
  timesketch/frontend-ng/src/components/Explore/EventActionMenu.vue
  timesketch/frontend-ng/src/components/Explore/EventDetail.vue
  timesketch/frontend-ng/src/components/Explore/EventList.vue
  timesketch/frontend-ng/src/components/Explore/TimelineChip.vue
  timesketch/frontend-ng/src/components/Explore/TimelineComponent.vue
  timesketch/frontend-ng/src/components/LeftPanel/TimelinesTable.vue
  timesketch/frontend-ng/src/components/SettingsDialog.vue
  timesketch/frontend-ng/src/components/Visualization/AggregationEventSelect.vue
  timesketch/frontend-ng/src/components/Visualization/VisualizationEditor.vue
  timesketch/frontend-ng/src/store.js
  timesketch/frontend-ng/src/utils/RestApiClient.js
  timesketch/frontend-ng/src/views/Analyze.vue
  timesketch/frontend-ng/src/views/Sketch.vue
  timesketch/lib/forms.py
  timesketch/lib/utils.py
  timesketch/models/sketch.py
Labels: Backend

#2919 Add Timeline, SearchIndex and Datasource creation to client api
  api_client/python/timesketch_api_client/client.py
  api_client/python/timesketch_api_client/sketch.py
Labels: API client
