Repository google/timesketch, pull requests merged in 2025-07, with the labels that each got.

#3458 Batch tags v3
  timesketch/frontend-v3/src/components/Explore/EventList.vue
  timesketch/frontend-v3/src/components/Explore/EventTagDialog.vue
  timesketch/frontend-v3/src/components/Explore/EventTagMenu.vue
Labels: Frontend

#3460 Update README.md
  README.md
Labels: Documentation

#3464 Update upgrade.md
  docs/guides/admin/upgrade.md
Labels: Documentation

#3462 Fix: Correctly parse microsecond epoch timestamps in CSV files
  tests/test_events/csv_timestamp_as_datetime.csv
  timesketch/lib/utils.py
  timesketch/lib/utils_test.py
Labels: Data import

#3468 Call validate_on_submit() on the login form.
  timesketch/views/auth.py
Labels: Bug
